### ISSUE TITLE
Hosting with Web Listener Fails - Request Not Supported error

### ISSUE THREAD

**Issue by sankar1204** [aspnet/Hosting#1025]
Hi,
we are using web listener for hosting  our asp net core mvc application, using below code
```
 var uri = new UriBuilder(new Uri(inputConfig.BaseLocation));
            uri.Host = "0.0.0.0";
            var config = new ConfigurationBuilder()
                .Build();
            host = new WebHostBuilder()
                .UseConfiguration(config)
                .UseUrls(uri.Uri.ToString())
                .ConfigureServices(ConfigureServices)
                .UseStartup<**Startup**>()
                .UseWebListener(options => {
                    options.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.None;
                    options.ListenerSettings.Authentication.AllowAnonymous = true;
                }).Build();
            host.Start();
```
And StartUp.cs 

```
    public class Startup    {
        public Startup(IHostingEnvironment env)   {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        public void ConfigureServices(IServiceCollection services)        {
            // Add framework services.
            services.AddMvc(options => {
                options.InputFormatters.Insert(0, new ResourceFormatter());
                options.OutputFormatters.Insert(0, new ResourceFormatter());
                options.Filters.Add(typeof(FhirExceptionFilterAttribute));
            });
        }

         public void Configure(IApplicationBuilder app, IHostingEnvironment env,
            ILoggerFactory loggerFactory)        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            //loggerFactory.AddDebug();
            app.UseMvc(builder => builder.MapRoute("ResourceNotFound", "{controller=Fhir}"));
        }
    }
}
```

but we get below core 
WebListenerException Occurred - {"The request is not supported"}
```
Stack trace:
   at Microsoft.Net.Http.Server.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.Net.Http.Server.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
   at Microsoft.Net.Http.Server.WebListener.Start()
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Philips.Platform.FhirNetCore.Server.Host.Start() in 
Host.cs:line 137
```

Not able to figure out whats wrong, need help here. Thanks in advance.

**Comment by Tratcher** [comment]
What's the resulting value passed into UseUrls?

**Comment by sankar1204** [comment]
@Tratcher  

http://localhost/somestring/
we are actually looking for port sharing on windows.
That's why we are using weblistener, even http://localhost:8080/somestring/ didn't work

**Comment by Tratcher** [comment]
That's not the final value. What's the output of `uri.Uri.ToString()`?

**Comment by sankar1204** [comment]
uri.URI.ToString() -> http://0.0.0.0/Somestring/

Since we want to listen to any request on this address we have put 0.0.0.0 in place of localhost.

**Comment by Tratcher** [comment]
The recommended syntax for that is "http://+:80/" or "http://*:80/" (which aren't formats supported by System.Uri).

**Comment by sankar1204** [comment]
@Tratcher  Thanks that worked.

uri.Uri.ToString() - this was causing problem. We should ve used uri.ToString() along with + / *
