### ISSUE TITLE
Hosting says that startup assembly was loaded even if it actually was not

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Hosting#1105]
```
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly WebCoreApp2.0
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly NonExistentThing
critHosting environment: Development
: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
      Hosting startup assembly exception
System.InvalidOperationException: Startup assembly NonExistentThing failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundExce
ption: Could not load file or assembly 'NonExistentThing, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
Content root path: C:\Users\xxxx\source\repos\WebCoreApp2.0\WebCoreApp2.0
Now listening on: http://localhost:58983
Application started. Press Ctrl+C to shut down.
```

Notice this line in the log:
```
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly NonExistentThing
```
Note that the exception is cached and we actually know when writing the log that something went wrong.

**Comment by davidfowl** [comment]
This came up when I originally did the logging. I didn't think it was worth storing (assembly, exception) since the exception would also be logged.

**Comment by muratg** [comment]
Closing this as wontfix. We may revisit if customers are confused with this.
