### ISSUE TITLE
ObjectDisposedException when using WebListener and IP address

### ISSUE THREAD

**Issue by Eilon** [aspnet/Hosting#1110]
_From @twenzel on April 4, 2017 13:0_

I can reproduce following error when starting my ASP.NET Core application as console:
```
2017-04-04T14:43:34.1364025+02:00 800004d6-0000-f400-b63f-84710c7967bb [ERR] ProcessRequestAsync (67a2badb)
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Net.Http.Server.ResponseStream'.
   at Microsoft.Net.Http.Server.ResponseStream.CheckDisposed()
   at Microsoft.Net.Http.Server.ResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.WebListener.ResponseStream.<WriteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.<FlushInternalAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.<ProcessRequestAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.<ProcessRequestAsync>d__24.MoveNext()
2017-04-04T14:43:34.1394037+02:00 800004d6-0000-f400-b63f-84710c7967bb [INF] Request finished in 336.4424ms 200 text/html; charset=utf-8 (15c52c40)
```

This happens only when using WebListener and a Ip address within the url:
```
  var host = new WebHostBuilder()
				 .UseWebListener()				
				.UseUrls("http://localhost:5000", "http://18.22.15.132:5000")
				.UseContentRoot(Directory.GetCurrentDirectory())                
                .UseStartup<Startup>()                
                .Build();

            host.Run();
```
The strange this is, this happens after 10-20s after starting. Something from the internal is requesting my HomeController:
```
   at ASPCoreBug.HomeController..ctor()
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.ApplicationWrapper`1.ProcessRequestAsync(Object context)
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.<ProcessRequestAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.ProcessRequestAsync(Object requestContextObj)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I'm using the latest versions.
Check the attached project to reproduce the issue (ensure to start the console hosted version).
[ASPCoreBug.zip](https://github.com/aspnet/Mvc/files/893177/ASPCoreBug.zip)

_Copied from original issue: aspnet/Mvc#6067_

**Comment by Eilon** [comment]
@Tratcher / @rynowak - any idea on this?

**Comment by Eilon** [comment]
_From @rynowak on April 12, 2017 17:10_

~~The second stack trace is #5807 - no idea about the first.~~

Actually strike that, the second stack trace isn't a bug, that's just a typical stack of creating a controller.

**Comment by Eilon** [comment]
_From @Tratcher on April 12, 2017 22:55_

Looks similar to https://github.com/aspnet/Hosting/issues/603 but it was never reproduced.

**Comment by Eilon** [comment]
_From @rynowak on June 19, 2017 8:48_

@eilon - we have a provided repro of this, someone should investigate

**Comment by Eilon** [comment]
@Tratcher - can you see if the repro works for you?

**Comment by Tratcher** [comment]
That app wouldn't even run when I tried it. Errors about MVC not being able to load various assemblies. I upgraded the sample to 2.0 preview2 and was able to run the sample but did not see the above errors.

**Comment by Tratcher** [comment]
@twenzel if you can still reproduce this issue let me know. Preferably with a 2.0 sample.

**Comment by twenzel** [comment]
I investigate a little bit more into this.
You can reproduce this by creating a request e.g. http://localhost:5000 with "HEAD" method (instead of "GET").

**Comment by twenzel** [comment]
This issue seems to be fixed in Core 2.0. After upgrading to 2.0 Preview 2 the error is not reproducible anymore.

**Comment by twenzel** [comment]
@Tratcher Does the repro works for you?

**Comment by Tratcher** [comment]
I did not investigate further since you said it no longer reproduced in 2.0.
