### ISSUE TITLE
[TestServer] Exception when using multiple IFormFile streams simultaneously

### ISSUE THREAD

**Issue by axel-habermaier** [aspnet/Hosting#1116]
There seems to be an issue with the ``TestServer`` when multiple ``IFormFile`` streams are open simultaneously. When using Kestrel, on the other hand, the bug does not appear, so this only affects our integration tests.

**Steps to reproduce**
- Create a new .NET Core 1.1 console application in VS 2017.
- Add the following to the project file:
```
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
		<PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.2" />
	</ItemGroup>
```
- Replace the code in ``Program.cs`` with the following:
```csharp
namespace ConsoleApp1
{
	using System;
	using System.IO;
	using System.Net.Http;
	using System.Threading.Tasks;
	using Microsoft.AspNetCore.Builder;
	using Microsoft.AspNetCore.Hosting;
	using Microsoft.AspNetCore.Http;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.TestHost;
	using Microsoft.Extensions.DependencyInjection;

	public class Startup
	{
		static void Main(string[] args)
		{
			var server = new TestServer(new WebHostBuilder().Configure(app => app.UseMvcWithDefaultRoute()).ConfigureServices(s => s.AddMvc()));

			var client = server.CreateClient();
			Request(client, "works");
			Request(client, "doesnotwork");
		}

		static void Request(HttpClient client, string method)
		{
			var content = new MultipartFormDataContent();
			content.Add(new StreamContent(new MemoryStream(new byte[100])), "a", "a");
			content.Add(new StreamContent(new MemoryStream(new byte[100])), "b", "b");

			var request = new HttpRequestMessage(HttpMethod.Post, $"/test/{method}");
			request.Content = content;

			client.SendAsync(request).Wait();
		}
	}

	[Route("test")]
	public class TestController : Controller
	{
		[HttpPost("works")]
		public async Task Works(IFormFile a, IFormFile b)
		{
			var f1 = System.IO.File.OpenWrite("a1");
			await a.OpenReadStream().CopyToAsync(f1);

			var f2 = System.IO.File.OpenWrite("a2");
			await b.OpenReadStream().CopyToAsync(f2);
		}

		[HttpPost("doesnotwork")]
		public async Task DoesNotWork(IFormFile a, IFormFile b)
		{
			var s1 = a.OpenReadStream();
			var s2 = b.OpenReadStream();

			var f1 = System.IO.File.OpenWrite("a3");
			await s1.CopyToAsync(f1);

			var f2 = System.IO.File.OpenWrite("a4");
			await s2.CopyToAsync(f2);
		}
	}
}
```
- Run the application.

**Expected results**
The application should quit normally, writing the four files.

**Actual results**
The application crashes with an ``InvalidOperationException`` (nested in an ``AggregateException``, but that's besides the point) when executing ``DoesNotWork``:

Message: The inner stream position has changed unexpectedly.
Stacktrace: 
 at Microsoft.AspNetCore.Http.Internal.ReferenceReadStream.VerifyPosition()
   at Microsoft.AspNetCore.Http.Internal.ReferenceReadStream.<ReadAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.TestController.<DoesNotWork>d__1.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()

**Comment by Tratcher** [comment]
This isn't specific to TestServer, IFormFile would have this problem any time the request body was seekable / fully buffered. When the body isn't seekable then the files are buffered individually.
https://github.com/aspnet/HttpAbstractions/blob/2ce2d8b6c5c4d3111f5bbfe642c478f229bd955f/src/Microsoft.AspNetCore.Http/Features/FormFeature.cs#L178-L203

In your specific case I think MultipartFormDataContent.ReadAsStreamAsync creates a seekable stream.

**Comment by muratg** [comment]
Non-supported case.
