### ISSUE TITLE
TestWebSocket throw Cannot access a disposed object on CloseAsync 

### ISSUE THREAD

**Issue by SleepyDeb** [aspnet/Hosting#1181]
Using Asp net core 2.0.0
I have an xunit library that start a TestHost and then connect to it using WebSocketClient,

On websocket close:
await ws.CloseAsync(WebSocketCloseStatus.Empty, "", CancellationToken.None);

I have this result:
at Microsoft.AspNetCore.TestHost.TestWebSocket.ReceiverSenderBuffer.ThrowNoReceive()
   at Microsoft.AspNetCore.TestHost.TestWebSocket.ReceiverSenderBuffer.<ReceiveAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.TestWebSocket.<ReceiveAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.TestWebSocket.<CloseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xxx.xxx.xxx.<WebSocketTest>d__6.MoveNext() in C:\Develop\srv\xxxxx.Test\IntegrationTest.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Messaggio risultato :	
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.TestHost.TestWebSocket'.

**Comment by SleepyDeb** [comment]
ok, there was a Receive in pending on another thread, sorry

But the exception is not clear
