### ISSUE TITLE
 Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.ShutdownTestWaitForShutdown fails on linux

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1214]
```
[xUnit.net 00:00:44.3372819]         | TestLifetime Information: Finished test ShutdownTestWaitForShutdown in 43.2488036s
Failed   Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.ShutdownTestWaitForShutdown
Error Message:
 System.Exception : dotnet publish exited with exit code : 1
Stack Trace:
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.DotnetPublish(String publishRoot) in /home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/ApplicationDeployer.cs:line 49
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<DeployAsync>d__7.MoveNext() in /home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/SelfHostDeployer.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.<ShutdownTestWaitForShutdown>d__2.MoveNext() in /home/travis/build/aspnet/Hosting/test/Microsoft.AspNetCore.Hosting.FunctionalTests/ShutdownTests.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Standard Output Messages:
 | TestLifetime Information: Starting test ShutdownTestWaitForShutdown
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=Shutdown
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "/tmp/a21409d7-5f5d-442f-b9c8-41a997bc33bf" --framework netcoreapp2.0 --configuration Debug 
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Hosting.Server.Abstractions -> /home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting.Server.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.Extensions.Hosting.Abstractions -> /home/travis/build/aspnet/Hosting/src/Microsoft.Extensions.Hosting.Abstractions/bin/Debug/netstandard2.0/Microsoft.Extensions.Hosting.Abstractions.dll
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Hosting.Abstractions -> /home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Hosting.Abstractions.dll
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018: System.IO.IOException: The process cannot access the file '/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Hosting.deps.json' because it is being used by another process. [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at System.IO.FileStream.Init(FileMode mode, FileShare share) [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /home/travis/.dotnet/sdk/2.1.0-preview1-007042/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj]
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Error: dotnet publish exited with exit code : 1
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Host process already exited or never started successfully.
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Failed to delete directory : Could not find a part of the path '/tmp/a21409d7-5f5d-442f-b9c8-41a997bc33bf'.
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Failed to delete directory : Could not find a part of the path '/tmp/a21409d7-5f5d-442f-b9c8-41a997bc33bf'.
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Failed to delete directory : Could not find a part of the path '/tmp/a21409d7-5f5d-442f-b9c8-41a997bc33bf'.
 | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '43.231047' seconds
 | TestLifetime Information: Finished test ShutdownTestWaitForShutdown in 43.2488036s
```

**Comment by muratg** [comment]
@Tratcher could you take a look please?

**Comment by JunTaoLuo** [comment]
Specifically:
```
System.IO.IOException: The process cannot access the file '/home/travis/build/aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Hosting.deps.json' because it is being used by another process.
```

**Comment by jkotalik** [comment]
Test is still failing on CI. Error message: 
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Stopping firing\nStopping end\nStopped firi···
Actual:   
          ↑ (pos 0)
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.<ExecuteShutdownTest>d__5.MoveNext() in /datadrive/33bdfc1cae7b2a38/modules/Hosting/test/Microsoft.AspNetCore.Hosting.FunctionalTests/ShutdownTests.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.<ShutdownTestWaitForShutdown>d__4.MoveNext() in /datadrive/33bdfc1cae7b2a38/modules/Hosting/test/Microsoft.AspNetCore.Hosting.FunctionalTests/ShutdownTests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| TestLifetime Information: Starting test ExecuteShutdownTest
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=Shutdown
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "/home/aspnetagent/buildAgent/temp/buildTmp/eef376fa-0d72-4b4d-999d-cd94903054b4" --framework netcoreapp2.0 --configuration Debug --no-restore 
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.5.172.19382 for .NET Core
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Hosting.Server.Abstractions -> /datadrive/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.AspNetCore.Hosting.Server.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.Extensions.Hosting.Abstractions -> /datadrive/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.Extensions.Hosting.Abstractions/bin/Debug/netstandard2.0/Microsoft.Extensions.Hosting.Abstractions.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Hosting.Abstractions -> /datadrive/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.AspNetCore.Hosting.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Hosting.Abstractions.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Hosting -> /datadrive/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.AspNetCore.Hosting/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Hosting.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Hosting.TestSites -> /datadrive/33bdfc1cae7b2a38/modules/Hosting/test/TestAssets/Microsoft.AspNetCore.Hosting.TestSites/bin/Debug/netcoreapp2.0/Microsoft.AspNetCore.Hosting.TestSites.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Hosting.TestSites -> /home/aspnetagent/buildAgent/temp/buildTmp/eef376fa-0d72-4b4d-999d-cd94903054b4/
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet publish finished with exit code : 0
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet /home/aspnetagent/buildAgent/temp/buildTmp/eef376fa-0d72-4b4d-999d-cd94903054b4/Microsoft.AspNetCore.Hosting.TestSites.dll --server.urls http://localhost:54434/  --server Microsoft.AspNetCore.Server.Kestrel
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=Shutdown
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_STARTMECHANIC=WaitForShutdown
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 49115
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://localhost:54434/
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Started
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: host process ID 49115 shut down
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Host process shutting down.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Host process already exited or never started successfully.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '60.789394' seconds
| TestLifetime Information: Finished test ExecuteShutdownTest in 60.8155421s
```

**Comment by muratg** [comment]
@jkotalik still an issue?

**Comment by jkotalik** [comment]
Believe this is under @JunTaoLuo workload. Test is currently disabled due to flakiness. We can try to re-enable later.

**Comment by muratg** [comment]
Closing this. We have other tracking issues for enabling disabled tests.
