### ISSUE TITLE
TestServer does not mark the response headers collection as read-only on start

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#1253]
When the response starts the server is supposed to mark the response header collection as read-only and throw if there are further attempts to modify it. TestServer isn't doing this right now and it may be hiding bugs in product components.  Flaky test failures like the following imply that there are at least some test issues being masked by this.
http://aspnetci/viewLog.html?buildId=351869&tab=buildResultsDiv&buildTypeId=Lite_MvcTest
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.FunctionalTests.FiltersTest.<OrderOfExecutionOfFilters_WhenOrderAttribute_IsNotMentioned>d__17.MoveNext() in C:\b\w\33bdfc1cae7b2a38\.r\Mvc\test\Microsoft.AspNetCore.Mvc.FunctionalTests\FiltersTest.cs:line 234
```

Perhaps we should add this functionality to the HeaderDictionary in HttpAbstractions. HttpSysServer has it's own private implementation that could be replaced by a shared version with this functionality.
https://github.com/aspnet/HttpAbstractions/blob/c0f937239a0a099b73c67c96ab9e1c875952f67f/src/Microsoft.AspNetCore.Http/HeaderDictionary.cs
https://github.com/aspnet/HttpSysServer/blob/db210af712e39b9e396e8f86826b0da42a3e5ee2/shared/Microsoft.AspNetCore.HttpSys.Sources/RequestProcessing/HeaderCollection.cs

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/Hosting/issues/1197
