### ISSUE TITLE
FileNotFoundException when creating an instance of TestServer

### ISSUE THREAD

**Issue by candoumbe** [aspnet/Hosting#1320]
Hi everyone,

i'm trying to create integration tests for a web api i'm building.
Tests unfortunately fail with a System.IO.FileNotFoundException when I run them

Here is the test I'm running
```
[Collection("IntegrationTests")]
    public class PatientsControllerTests : IDisposable, IClassFixture<ServicesTestFixture<Startup>>
    {
        private HttpClient _client;
        private ITestOutputHelper _outputHelper;

        public PatientsControllerTests(ITestOutputHelper outputHelper, ServicesTestFixture<Startup> fixture)
        {
            _outputHelper = outputHelper;
            fixture.Initialize(Path.Combine("..", "..", "..", "..", "src", "services", "Measures"));
            _client = fixture.Client;
        }


        public void Dispose()
        {
            _outputHelper = null;
            _client.Dispose();

        }

        [Theory]
        [InlineData("/")]
        [InlineData("/measures")]
        public async Task Calling_Index_Returns_Root_Informations(string url)
        {
            // Act
            HttpResponseMessage response = await _client.GetAsync(url).ConfigureAwait(false);

            // Assert
            response.StatusCode.Should().Be(StatusCodes.Status200OK);
            response.Headers.Should()
                .ContainSingle(header => "Content-Type".Equals(header.Key))
                .Which.Value.Should()
                .ContainSingle(val => val == "application/json");


            string json = await response.Content.ReadAsStringAsync();
            
        }
```

The fixture :

```
// <summary>
    /// A test fixture which hosts the target project (project we wish to test) in an in-memory server.
    /// </summary>
    /// <typeparam name="TStartup">Target project's startup type</typeparam>
    public abstract class BaseTestFixture<TStartup> : IDisposable
    {
        private TestServer _server;

        protected BaseTestFixture()
        { 
        }

        public virtual void Initialize(string relativeTargetProjectParentDir)
        {
            Assembly startupAssembly = typeof(TStartup).GetTypeInfo().Assembly;
            string contentRoot = GetProjectPath(relativeTargetProjectParentDir, startupAssembly);
            string environmentName = "Development";

            IConfiguration configuration = new ConfigurationBuilder()
                .SetBasePath(contentRoot)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{environmentName}.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();

            IHostingEnvironment env = new HostingEnvironment
            {
                ContentRootPath = contentRoot,
                EnvironmentName = environmentName,
                ApplicationName = "Measures.API",
                ContentRootFileProvider = new NullFileProvider(),
                WebRootFileProvider = null,
                WebRootPath = null
            };

            IWebHostBuilder builder = new WebHostBuilder()
                //.UseContentRoot(contentRoot)
                .UseConfiguration(configuration)
                .UseEnvironment("Development")
                .ConfigureServices(InitializeServices)
                .ConfigureServices(services => services.AddSingleton(env))
                .UseStartup(typeof(TStartup))
                ;
            
            _server = new TestServer(builder);

            Client = _server.CreateClient();
            Client.BaseAddress = new Uri("http://localhost");
        }
        

        public HttpClient Client { get; protected set; }

        public void Dispose()
        {
            Client?.Dispose();
            _server?.Dispose();
        }

        protected virtual void InitializeServices(IServiceCollection services)
        {
            Assembly startupAssembly = typeof(TStartup).GetTypeInfo().Assembly;

            // Inject a custom application part manager. 
            // Overrides AddMvcCore() because it uses TryAdd().
            ApplicationPartManager manager = new ApplicationPartManager();
            manager.ApplicationParts.Add(new AssemblyPart(startupAssembly));
            manager.FeatureProviders.Add(new ControllerFeatureProvider());
            manager.FeatureProviders.Add(new ViewComponentFeatureProvider());
            
            services.AddSingleton(manager);
        }

        /// <summary>
        /// Gets the full path to the target project that we wish to test
        /// </summary>
        /// <param name="projectRelativePath">
        /// The parent directory of the target project.
        /// e.g. src, samples, test, or test/Websites
        /// </param>
        /// <param name="startupAssembly">The target project's assembly.</param>
        /// <returns>The full path to the target project.</returns>
        private static string GetProjectPath(string projectRelativePath, Assembly startupAssembly)
        {
            // Get name of the target project which we want to test
            string projectName = startupAssembly.GetName().Name;

            // Get currently executing test project path
            string applicationBasePath = AppContext.BaseDirectory;

            // Find the path to the target project
            DirectoryInfo directoryInfo = new DirectoryInfo(applicationBasePath);
            string[] directoryParts = projectRelativePath.Split(Path.DirectorySeparatorChar);
            int goToParentDirectory = 0;
            foreach (string part in directoryParts)
            {
                switch (part)
                {
                    case "..":
                        directoryInfo = directoryInfo.Parent;
                        goToParentDirectory++;
                        break;
                    case ".": break;
                    case null: break;
                    default:
                        string[] oldPath = directoryInfo.FullName.Split(Path.DirectorySeparatorChar);
                        string newPath = string.Join(Path.DirectorySeparatorChar, oldPath.Take(oldPath.Length - 1));
                        directoryInfo = new DirectoryInfo(Path.Combine(newPath, part));
                        break;
                }
            }
            projectRelativePath = string.Join(Path.DirectorySeparatorChar, directoryParts.Skip(goToParentDirectory));

            do
            {
                directoryInfo = directoryInfo.Parent;
                DirectoryInfo projectDirectoryInfo = new DirectoryInfo(Path.Combine(directoryInfo.FullName, projectRelativePath));
                if (projectDirectoryInfo.Exists)
                {
                    FileInfo projectFileInfo = new FileInfo(Path.Combine(projectDirectoryInfo.FullName, projectName, $"{projectName}.csproj"));
                    if (projectFileInfo.Exists)
                    {
                        return Path.Combine(projectDirectoryInfo.FullName, projectName);
                    }
                }
            }
            while (directoryInfo.Parent != null);

            throw new Exception($"Project root could not be located using the application root {applicationBasePath}.");
        }
    }
```

The startup class of the SUT

```
using FluentValidation.AspNetCore;
using Measures.API.Context;
using Measures.API.Routing;
using Measures.API.StartupRegistration;
using Measures.Mapping;
using Measures.Validators;
using MedEasy.DAL.Context;
using MedEasy.DAL.Interfaces;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.PlatformAbstractions;
using Newtonsoft.Json.Serialization;
using Swashbuckle.AspNetCore.Swagger;
using System.IO;
using Newtonsoft.Json;
using static Newtonsoft.Json.DateFormatHandling;
using static Newtonsoft.Json.DateTimeZoneHandling;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Cors.Internal;

namespace Measures.API
{
    /// <summary>
    /// Startup class
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// The root configuration 
        /// </summary>
        public IConfiguration Configuration { get; }

        /// <summary>
        /// Provides information about 
        /// </summary>
        public IHostingEnvironment HostingEnvironment { get; }

        /// <summary>
        /// Builds a new <see cref="Startup"/> instance.
        /// </summary>
        /// <param name="env">Accessor to the current ost's environment </param>
        /// <param name="configuration">configuration provided by the host</param>
        public Startup(IHostingEnvironment env, IConfiguration configuration)
        {
            Configuration = configuration;
            HostingEnvironment = env;
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc(options =>
            {
                options.Filters.Add(typeof(FormatFilter));
                //options.Filters.Add(typeof(ValidateModelAttribute));
                ////options.Filters.Add(typeof(EnvelopeFilterAttribute));
                //options.Filters.Add(typeof(HandleErrorAttribute));
                options.OutputFormatters.Add(new XmlDataContractSerializerOutputFormatter());

            })
            .AddJsonOptions(options =>
            {
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                options.SerializerSettings.DateFormatHandling = IsoDateFormat;
                options.SerializerSettings.DateTimeZoneHandling = Utc;
                options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                options.SerializerSettings.Formatting = Formatting.Indented;
                options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

            })
            .AddFluentValidation(options =>
            {
                options.LocalizationEnabled = true;
                options.RegisterValidatorsFromAssemblyContaining<CreateBloodPressureInfoValidator>();
            });

            services.AddCors(options =>
            {
                options.AddPolicy("AllowAnyOrigin", builder => 
                    builder.AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowAnyOrigin()
                );
            });
            services.Configure<MvcOptions>(options =>
            {
                options.Filters.Add(new CorsAuthorizationFilterFactory("AllowAnyOrigin"));
            });

            services.AddSingleton(x => AutoMapperConfig.Build().CreateMapper().ConfigurationProvider.ExpressionBuilder);
            services.AddSingleton<IUnitOfWorkFactory, EFUnitOfWorkFactory<MeasuresContext>>(item =>
            {
                DbContextOptionsBuilder<MeasuresContext> builder = new DbContextOptionsBuilder<MeasuresContext>();
                builder.UseSqlServer(Configuration.GetConnectionString("Measures"));

                return new EFUnitOfWorkFactory<MeasuresContext>(builder.Options, (options) => new MeasuresContext(options));

            });
            services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddScoped(builder =>
            {
                IUrlHelperFactory urlHelperFactory = builder.GetRequiredService<IUrlHelperFactory>();
                IActionContextAccessor actionContextAccessor = builder.GetRequiredService<IActionContextAccessor>();

                return urlHelperFactory.GetUrlHelper(actionContextAccessor.ActionContext);
            });


            services.AddValidators();

            services.AddOptions();
            services.Configure<MeasuresApiOptions>((options) =>
            {
                options.DefaultPageSize = Configuration.GetValue("APIOptions:DefaultPageSize", 30);
                options.MaxPageSize = Configuration.GetValue("APIOptions:MaxPageSize", 100);
            });

            if (HostingEnvironment.IsDevelopment())
            {
                ApplicationEnvironment app = PlatformServices.Default.Application;
                services.AddSwaggerGen(config =>
                {
                    config.SwaggerDoc("v1", new Info
                    {
                        Title = app.ApplicationName,
                        Description = "REST API for Measures API",
                        Version = "v1",
                        Contact = new Contact
                        {
                            Email = Configuration.GetValue("Swagger:Contact:Email", string.Empty),
                            Name = Configuration.GetValue("Swagger:Contact:Name", string.Empty),
                            Url = Configuration.GetValue("Swagger:Contact:Url", string.Empty)
                        }
                    });
                    
                    config.IgnoreObsoleteActions();
                    config.IgnoreObsoleteProperties();
                    config.IncludeXmlComments(Path.Combine(app.ApplicationBasePath, $"{app.ApplicationName}.xml"));
                    config.DescribeStringEnumsInCamelCase();
                    config.DescribeAllEnumsAsStrings();
                });
            }
            services.AddRouting(options =>
            {
                options.AppendTrailingSlash = true;
                options.LowercaseUrls = true;
            });

        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// 
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        /// <param name="loggerFactory"></param>
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (!env.IsDevelopment())
            {
                app.UseResponseCaching();
                app.UseResponseCompression();
            }
            else
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();

                app.UseSwagger();
                app.UseSwaggerUI(opt =>
                {
                    opt.SwaggerEndpoint("/swagger/v1/swagger.json", "MedEasy REST API V1");
                });

            }

            app.UseCors("AllowAnyOrigin");
            app.UseMvc(routeBuilder =>
            {
                routeBuilder.MapRoute(RouteNames.Default, "measures/{controller=root}/{action=index}");
                routeBuilder.MapRoute(RouteNames.DefaultGetOneByIdApi, "measures/{controller}/{id}");
                routeBuilder.MapRoute(RouteNames.DefaultGetAllApi, "measures/{controller}/");
                routeBuilder.MapRoute(RouteNames.DefaultGetOneSubResourcesByResourceIdAndSubresourceIdApi, "measures/{controller}/{id}/{action}/{subResourceId}");
                routeBuilder.MapRoute(RouteNames.DefaultGetAllSubResourcesByResourceIdApi, "measures/{controller}/{id}/{action}/");
                routeBuilder.MapRoute(RouteNames.DefaultSearchResourcesApi, "measures/{controller}/search/");
            });
        }
    }
}

```

The .csproj file of the test project
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="FluentAssertions" Version="4.19.4" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\services\Measures\Measures.API\Measures.API.csproj" />
  </ItemGroup>

</Project>
```
The exception stacktrace
```
Test name :	Measures.API.IntegrationTests.PatientsControllerTests.Calling_Index_Returns_Root_Informations(url: "/")
FullName de test :	Measures.API.IntegrationTests.PatientsControllerTests.Calling_Index_Returns_Root_Informations
Source de test :	C:\Users\ndoum\Documents\Visual Studio 2017\Projects\MedEasy\test\services\measures\Measures.API.IntegrationTests\PatientsControllerTests.cs : ligne 38
Sortie du test :	Échec
Durée du test :	0:00:00,001

StackTrace de résultat  :	
at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass25_0.<IncludeXmlComments>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Measures.API.IntegrationTests.BaseTestFixture`1.Initialize(String relativeTargetProjectParentDir) in C:\Users\ndoum\Documents\Visual Studio 2017\Projects\MedEasy\test\services\measures\Measures.API.IntegrationTests\BaseTestFixture.cs:line 62
   at Measures.API.IntegrationTests.PatientsControllerTests..ctor(ITestOutputHelper outputHelper, ServicesTestFixture`1 fixture) in C:\Users\ndoum\Documents\Visual Studio 2017\Projects\MedEasy\test\services\measures\Measures.API.IntegrationTests\PatientsControllerTests.cs:line 23
Message de résultat  :	System.IO.FileNotFoundException : Could not find file 'C:\Users\ndoum\Documents\Visual Studio 2017\Projects\MedEasy\test\services\measures\Measures.API.IntegrationTests\bin\Debug\netcoreapp2.0\testhost.xml'.

```

Am I doing something wrong ?

**Comment by candoumbe** [comment]
After looking (more) carefully at the stacktrace I submitted, it occured that this bug is not relaterd to `TestServer` but to `Swashbuckle`. I'll report the issue to them.

Sorry for the inconvenience.

**Comment by candoumbe** [comment]
@aledaccas

Thanks toute for pointing that out. I manage to get rid of the error by simply checking the presence of the file before trying to include it 😉

**Comment by candoumbe** [comment]
@gersoncardosofilho 
Simply wrap the line in `if`

```csharp
string documentationFile =Path.Combine(app.ApplicationBasePath, $"{app.ApplicationName}.xml");
                    
if(File.Exists("/path/to/the/documentation/file"){
    // here we know that the documentation file exists
    config.IncludeXmlComments(Path.Combine(app.ApplicationBasePath, $"{app.ApplicationName}.xml"));
}
```

**Comment by aledaccas** [comment]
The problem is the usage of this property (PlatformServices.Default.Application.ApplicationName)  in your code to define the documentation xml file in your web application project (See your Startup.cs class).
When you use the TestServer object, it replaces the PlatformServices.Default.Application.Application name from "YourAssemblyName" to "TestHost".

To solve it, you can use the solution made by candoumbe, checking if the xml file exists before include it in swagger, or you can hardcode your IncludeXmlComents filename with your assemblyname, Example:
`//Startup.cs
...
//instead of
config.IncludeXmlComments(Path.Combine(app.ApplicationBasePath, $"{app.ApplicationName}.xml"));
//replace the filename with your assembly (project) name
  config.IncludeXmlComments(Path.Combine(app.ApplicationBasePath, "your.project.name.xml"));
}
`

**Comment by gersoncardosofilho** [comment]
@candoumbe  and @aledaccas thanks for the tips, after a day trying, based on your tips, finally it works. Thank you very much.
