### ISSUE TITLE
Flaky test: dotnet publish sometimes fails saying the dll is locked

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#1357]
_From @jkotalik on March 17, 2018 1:48_

```c#
System.AggregateException : One or more errors occurred. (One or more errors occurred. (dotnet publish exited with exit code : 1)) (The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture)
---- System.AggregateException : One or more errors occurred. (dotnet publish exited with exit code : 1)
-------- System.Exception : dotnet publish exited with exit code : 1
---- The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture

----- Inner Stack Trace #1 (System.AggregateException) -----
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.IISTestSiteFixture..ctor() in C:\b\w\791c468639bcb5dc\test\IISIntegration.FunctionalTests\Utilities\IISTestSiteFixture.cs:line 36
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.DotnetPublish(String publishRoot)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer.DeployAsync()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

_Copied from original issue: aspnet/IISIntegration#690_

**Comment by ryanbrandenburg** [comment]
This is [still happening](http://aspnetci/viewLog.html?buildId=488543&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest) 100% of the time and fails ~65 test on every run. @muratg can we prioritize this issue?

**Comment by Eilon** [comment]
Thanks @jkotalik , let's get this done ASAP.

**Comment by jkotalik** [comment]
This specific isn't the same as what CI failure were occurring. It's hard to tell the difference. If you see other failures similar to this, please post an issue in IISIntegration and we will triage.
