### ISSUE TITLE
Windows 7: Can't start ASP.Net app without admin rights

### ISSUE THREAD

**Issue by StefanoD** [aspnet/Hosting#1363]
I can't start my ASP.Net Core App on Windows 7 without admin rights.
On Windows 10 I don't need any admin rights.

I'm using following packages:
```XML
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.2" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Https" Version="2.0.2" />
<PackageReference Include="Microsoft.Data.SQLite" Version="2.0.1" />
<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="2.0.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
```
This is the error message:
```
2018-03-22 14:27:29.1377|6|FATAL|Microsoft.AspNetCore.Hosting.Internal.WebHost|Application startup exception Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Zugriff verweigert
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at QLCConnectServer.Program.<>c.<BuildWebHost>b__1_2(ListenOptions listenOptions) in D:\development\ESLR22-SO-0010_Connect\sources\QLCConnectServer\QLCConnectServer\Program.cs:line 69
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure)
   at QLCConnectServer.Program.<>c__DisplayClass1_0.<BuildWebHost>b__0(KestrelServerOptions options) in D:\development\ESLR22-SO-0010_Connect\sources\QLCConnectServer\QLCConnectServer\Program.cs:line 78
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1 options, ITransportFactory transportFactory, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
2018-03-22 14:27:29.2313||ERROR|QLCConnectServer.Program|Stopped program because of exception Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Zugriff verweigert
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at QLCConnectServer.Program.<>c.<BuildWebHost>b__1_2(ListenOptions listenOptions) in D:\development\ESLR22-SO-0010_Connect\sources\QLCConnectServer\QLCConnectServer\Program.cs:line 69
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure)
   at QLCConnectServer.Program.<>c__DisplayClass1_0.<BuildWebHost>b__0(KestrelServerOptions options) in D:\development\ESLR22-SO-0010_Connect\sources\QLCConnectServer\QLCConnectServer\Program.cs:line 78
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1 options, ITransportFactory transportFactory, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at QLCConnectServer.Program.BuildWebHost(String[] args) in D:\development\ESLR22-SO-0010_Connect\sources\QLCConnectServer\QLCConnectServer\Program.cs:line 46
   at QLCConnectServer.Program.Main(String[] args) in D:\development\ESLR22-SO-0010_Connect\sources\QLCConnectServer\QLCConnectServer\Program.cs:line 25
```

This is my code:

```C#
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using System.Net;
using Microsoft.AspNetCore.Server.Kestrel.Https;
using System.Security.Cryptography.X509Certificates;
using System.Security.Authentication;
using QLCConnectServer.Controllers.Validators;
using NLog.Web;
using Microsoft.Extensions.Configuration;
using System.IO;
using System;
using NLog;

namespace QLCConnectServer
{
    public class Program
    {
        public static void Main(string[] args)
        {
            // NLog: setup the logger first to catch all errors
            var logger = LogManager.LoadConfiguration("nlog.config").GetCurrentClassLogger();
            try
            {
                logger.Debug("init main");
                BuildWebHost(args).Run();
            }
            catch (Exception ex)
            {
                //NLog: catch setup errors
                logger.Error(ex, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }
        }

        public static IWebHost BuildWebHost(string[] args)
        {
            var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json");

            var config = builder.Build();
            int pcClientPort = config.GetValue<int>("PCClientPort");
            int iswClientPort = config.GetValue<int>("ISWClientPort");

            return WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = 1024 * 1024 * 1024; // 1 GiB
                    options.Listen(IPAddress.Any, iswClientPort, listenOptions =>
                    {
                        listenOptions.UseHttps(new HttpsConnectionAdapterOptions
                        {
                            ServerCertificate = new X509Certificate2("isw_intermediate.pfx", "dummyPass"),
                            SslProtocols = SslProtocols.Tls | // Qt 4.8 compatibility
                                           SslProtocols.Tls11 |
                                           SslProtocols.Tls12,
                            ClientCertificateMode = ClientCertificateMode.RequireCertificate,
                            ClientCertificateValidation = new KestrelISWCertificateValidator("ISWCertificateValidation").ValidateClientCertificate
                        });
                    });
                    options.Listen(IPAddress.Any, pcClientPort, listenOptions =>
                    {
                        listenOptions.UseHttps(new HttpsConnectionAdapterOptions
                        {
                            ServerCertificate = new X509Certificate2("Server_Root_Certificate.pfx", "dummyPass"),
                            SslProtocols = SslProtocols.Tls11 |
                                           SslProtocols.Tls12,
                            //ClientCertificateMode = ClientCertificateMode.RequireCertificate,
                            //ClientCertificateValidation = new KestrelISWCertificateValidator("BrowserCertificateValidation").ValidateClientCertificate
                        });
                    });
                })
                .UseNLog()  // NLog: setup NLog for Dependency injection
                .Build();
        }
    }
}
```
Any ideas?

**Comment by Tratcher** [comment]
It looks like one of these lines:
`new X509Certificate2("isw_intermediate.pfx", "dummyPass")`.
`new X509Certificate2("Server_Root_Certificate.pfx", "dummyPass")`

Can you extract them out to their own console app for debugging?

**Comment by StefanoD** [comment]
It seems that only the second certificate makes problems. The exception says "Access denied" in German.

```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Zugriff verweigert
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at CertTest.Program.Main(String[] args) in C:\Users\MartinoS\source\repos\CertTest\CertTest\Program.cs:line 17
```

```C#
using System;
using System.IO;
using System.Security.Cryptography.X509Certificates;

namespace CertTest
{
    class Program
    {
        //private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();

        static void Main(string[] args)
        {
            try
            {
                var cert1 = new X509Certificate2(@"isw_intermediate.pfx", "dummyPass");
                Console.WriteLine(cert1.GetCertHashString());
                var cert2 = new X509Certificate2(@"Server_Root_Certificate.pfx", "dummyPass");
                Console.WriteLine(cert2.GetCertHashString());
                Console.ReadLine();
            }
            catch (Exception ex)
            {
                File.WriteAllText("log.txt", ex.ToString());
                //logger.Fatal(ex);
            }
        }
    }
}
```

**Comment by Tratcher** [comment]
That's pretty strange, I wonder if there's something new/special about that cert. You should send this to the folks at https://github.com/dotnet/corefx. I expect they'd need a dummy cert that reproduces the issue as well.

Does it work if you run the same app using .NET 4.x?

**Comment by Drawaes** [comment]
Have you checked the permissions on the cert in the store?

**Comment by StefanoD** [comment]
@Drawaes How do I do this? Is it a problem, if the certificate is self generated and a root certificate? It hasn't been signed by any CA.

**Comment by StefanoD** [comment]
I generated a new certificate which is not a root cert and it works now.
