### ISSUE TITLE
WebHost.RunAsync doesn't stop when Kestrel cannot listen on a particular port.

### ISSUE THREAD

**Issue by ravarnamsft** [aspnet/Hosting#1367]
I am using await webHost.RunAsync() in our .Net Core project (Nuget- Asp.NetCoreAll 2.0.3). On Ubuntu 16.04 (Azure VM), I am observing that whenever there is a port conflict, kestrel seems to throw an exception but the awaiting on webHost.RunAsync() doesn't throw or return a completed Task. This makes it harder for us to detect our application failure and take recovery action. Is this a known issue / fixed in later releases?

Here is the exception from kestrel:

2018-03-27T21:19:57.3909067+00:00  [FTL] Unable to start Kestrel. (fc6a528d)
System.IO.IOException: Failed to bind to address https://0.0.0.0:5002: address                                                                                                                                                              already in use. ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.                                                                                                                                                             Internal.AddressInUseException: Error -98 EADDRINUSE address already in use --->                                                                                                                                                              Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvExcep                                                                                                                                                             tion: Error -98 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.Li                                                                                                                                                             buvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.Uv                                                                                                                                                             TcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.List                                                                                                                                                             enTcp(Boolean useFileHandle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.<>c.                                                                                                                                                             <StartAsync>b__8_0(Listener listener)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.D                                                                                                                                                             oPostWork()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                                                                                                                                                             ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrima                                                                                                                                                             ry.<StartAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                                                                                                                                                             ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAs                                                                                                                                                             ync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAs                                                                                                                                                             ync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                                                                                                                                                             ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21                                                                                                                                                             _0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                                                                                                                                                             ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpo                                                                                                                                                             intAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpo                                                                                                                                                             intAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                                                                                                                                                             ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsS                                                                                                                                                             trategy.<BindAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                                                                                                                                                             ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync                                                                                                                                                             >d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot                                                                                                                                                             ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StartAsync>d__21`1                                                                                                                                                             .MoveNext()

Instead, if I just do the following, it seems to just work:
await host.StartAsync();
await host.WaitForShutdownAsync();

Most of the online documentation and the default VS project template uses Run/RunAsync, so I am not sure if I should directly use StartAsync and WaitForShutdownAsync. Looking at the RunAsync it does mostly the same thing with some additional ManualResetEvents.

**Comment by Tratcher** [comment]
This looks suspiciously like something we fixed in 2.1, though I can't find the work item. Can you try this on 2.1-preview1?

**Comment by ravarnamsft** [comment]
I will 2.1-preview1 a try and let you know how it goes.
