### ISSUE TITLE
flaky test: Microsoft.AspNetCore.TestHost.ClientHandlerTests.ClientCancellationAborts

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1379]
I've seen this happen twice now:

https://ci.appveyor.com/project/aspnetci/hosting/build/1.0.2650
https://ci.appveyor.com/project/aspnetci/hosting/build/1.0.2648

```
dotnet.exe : [xUnit.net 00:00:12.3149197]     Microsoft.AspNetCore.TestHost.ClientHandlerTests.ClientCancellationAborts [FAIL]
At C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview3-17002\scripts\common.psm1:7 char:5
+     & $_cmd @args
+     ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([xUnit.net 00:0...onAborts [FAIL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Failed   Microsoft.AspNetCore.TestHost.ClientHandlerTests.ClientCancellationAborts
Error Message:
 Assert.Throws() Failure
Expected: typeof(System.AggregateException)
Actual:   (No exception was thrown)
Stack Trace:
   at Microsoft.AspNetCore.TestHost.ClientHandlerTests.ClientCancellationAborts()
--- End of stack trace from previous location where exception was thrown ---
Application startup exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.AspNetCore.TestHost.TestServerTests.<>c.<CaptureStartupErrorsSettingPreserved>b__6_0(IApplicationBuilder app) in C:\projects\hosting\test\Microsoft.AspNetCore.TestHost.Tests\TestServerTests.cs:line 93
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication() in C:\projects\hosting\src\Microsoft.AspNetCore.Hosting\Internal\WebHost.cs:line 219
```

**Comment by Tratcher** [comment]
Interesting. The same test failed when I tried to clean up the pipe code. https://github.com/aspnet/Hosting/pull/1374

**Comment by davidfowl** [comment]
And again https://ci.appveyor.com/project/aspnetci/hosting/build/1.0.2651

**Comment by davidfowl** [comment]
Nice!
