### ISSUE TITLE
registering IHttpContextAccessor

### ISSUE THREAD

**Issue by ecabigting** [aspnet/Hosting#1380]
I already did the what was explained in [#793](https://github.com/aspnet/Hosting/issues/793)

This is a snippet from my startup.cs 

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddScoped<IMainHttpClient, MainHttpClient>();
            services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddScoped(sp => sp.GetRequiredService<IHttpContextAccessor>().HttpContext);
            services.AddSignalR();

            //for session
            services.AddDistributedMemoryCache();
            services.AddSession(options =>
            {
                options.Cookie.Name = "dcaaiiancookie";
                options.IdleTimeout = TimeSpan.FromSeconds(900);
            });
        }`

And still when I published, I still get the 
`Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Startup'` error.

I am publishing in IIS, with dotnet core module When I try to access the site it gives this error:

`An error occurred while starting the application.

.NET Core 4.6.26212.01 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.0.1-rtm-125    |    Microsoft Windows 6.3.9600    |   Need help? `

Please help! Im becoming desperate :(

**Comment by benaadams** [comment]
Switch logging on in the webconfig
```xml
<aspNetCore  ... stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
```
Then check what errors are written to the logs (or check the event log if nothing is written to the logs)

**Comment by ecabigting** [comment]
thanks @benaadams  for replying here is the full log I got

> Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Web.Startup'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Web.Startup'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by benaadams** [comment]
Do you need this line?
```
services.AddScoped(sp => sp.GetRequiredService<IHttpContextAccessor>().HttpContext);
```

**Comment by ecabigting** [comment]
I already removed it a while ago while testing, same error.

**Comment by ecabigting** [comment]
just did a fresh publish and got the same. Heres from the error log:

> Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'xxx_wow.Web.Startup'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'xxx_wow.Web.Startup'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: E:\wwwroot\xxx.wowsolution.com
Now listening on: http://localhost:16659
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://xxx.wowsolution.com/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 11.3508ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://xxx.wowsolution.com/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.6903ms 500 text/html; charset=utf-8

**Comment by benaadams** [comment]
Move the registration to first line and don't register anything for `HttpContext` (e.g. you should get it via `IHttpContextAccessor` if you need it for a service, or use regular DI elsewhere as its registered for you)
```csharp
public void ConfigureServices(IServiceCollection services) 
{ 
    services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>(); 
    // ...
```

**Comment by ecabigting** [comment]
I moved it to the first line, still the same error. Im using it for my controllers like this:

`    public class DashboardController : DaBaseController
    {
        private readonly IHttpContextAccessor _httpCtxtAcc;
        private ISession _session => _httpCtxtAcc.HttpContext.Session;

        public DashboardController(IHttpContextAccessor httpContextAccessor, )
        {
            _httpCtxtAcc = httpContextAccessor;

        }`

**Comment by benaadams** [comment]
Does `DaBaseController` inherit from `Controller` or `ControllerBase`?

If so you already have access to the `HttpContext` so can do
```csharp
public class DashboardController : DaBaseController
{
    private ISession _session => HttpContext.Session;
    public DashboardController()
    {
    
    }
```

**Comment by ecabigting** [comment]
It inherits from `Controller`

**Comment by benaadams** [comment]
So you shouldn't need `IHttpContextAccessor` for this purpose as `Controller` already has:
```csharp
// Summary:
//     Gets the Microsoft.AspNetCore.Http.HttpContext for the executing action.
public HttpContext HttpContext { get; }
```

**Comment by ecabigting** [comment]
Im not sure I am following, I need the `IHttpContextAccessor` to access `session`.

**Comment by benaadams** [comment]
> Im not sure I am following, I need the `IHttpContextAccessor` to access `session`.

`Session` is a property on `HttpContext` e.g. `HttpContext.Session`. You aren't getting a different one via `IHttpContextAccessor`.

`IHttpContextAccessor` is used for something out of flow of the pipleine, like inside something you'd register in `ConfigureServices` rather than regular controllers or something you set up in `Configure` which can have the `HttpContext` directly injected.

**Comment by ecabigting** [comment]
@benaadams Thank you so much ! I think I got it. I used `IHttpContextAccessor` because of an article I found to implement sessions. Thank you!

**Comment by benaadams** [comment]
You probably want to turn the webconfig logging back off ;)
```
 stdoutLogEnabled="false"
```

**Comment by ecabigting** [comment]
Yup! Thanks again, oh just a quick one, I tried removing all `IHttpContextAccessor` and replacing them with `HttpContext`  as you said, now `HttpContext` is null on controller constructor.

**Comment by benaadams** [comment]
I think `HttpContext` set just after the constructor? Or rather the [ControllerContext](https://github.com/aspnet/Mvc/blob/e52933e4e3ec3d5376d764cff32fcb3102ae902c/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L39) where it gets it from:
```csharp
public abstract class ControllerBase
{
    /// <summary>
    /// Gets the <see cref="Http.HttpContext"/> for the executing action.
    /// </summary>
    public HttpContext HttpContext => ControllerContext.HttpContext;
```

**Comment by ecabigting** [comment]
So was going back to my code, I need the `IHttpContextAccessor` in startup added to the services so it can be accessible when on **my** controller constructors. Now that was gone, I always have a null `HttpContext.Session`. Even before I set values for it. Can I have it instantiated so it wont be null?

**Comment by ecabigting** [comment]
@benaadams Thank you for all your work. I found a work around. Thank you so muych!

**Comment by michelmob** [comment]
@benaadams and @ecabigting  how are you guys doing? 

I guess I'm having the same problem here and maybe you can help me. After my authentication process, I'm adding a user value to :

HttpContext.Session.Set("UserCompanyId", value);

the problem is that in the next request the value is not there anymore. It seems is an async/await problem and threads/context. 

You had the same problem? Async context? 

Thank you in Advance.

**Comment by michelmob** [comment]
OK Guys!  my problem was that I was using this configuration

             services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

and I add,

   services.AddSession(options =>
            {
                options.Cookie.IsEssential = true;
            });


So, the consent policy will be bypassed.
