### ISSUE TITLE
Startup assembly StartupBootstrapper failed to execute

### ISSUE THREAD

**Issue by isualize** [aspnet/Hosting#1398]
Im getting this error in my logs currently:

2018-04-23 18:10:25.818 +00:00 [Fatal] Hosting startup assembly exception
System.InvalidOperationException: Startup assembly StartupBootstrapper failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---

Im using the following version of microsoft.aspnetcore:
\.nuget\packages\microsoft.aspnetcore\2.0.1\lib\netstandard2.0\Microsoft.AspNetCore.dll

Am i missing something or is this a known bug? Im hosting this in an Azure App Service.

**Comment by Tratcher** [comment]
We're going to need more than that, Can you share a repro app?

Any call to Assembly.Load is suspect. What are you trying to do?

**Comment by isualize** [comment]
Creating a repro app will take some time as this is (company) production code, but in essentially we're just doing this:

    `public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }`

Which in turn executes this:

                `// Execute the hosting startup assemblies
                foreach (var assemblyName in _options.GetFinalHostingStartupAssemblies().Distinct(StringComparer.OrdinalIgnoreCase))
                {
                    try
                    {
                        var assembly = Assembly.Load(new AssemblyName(assemblyName));

                        foreach (var attribute in assembly.GetCustomAttributes<HostingStartupAttribute>())
                        {
                            var hostingStartup = (IHostingStartup)Activator.CreateInstance(attribute.HostingStartupType);
                            hostingStartup.Configure(this);
                        }
                    }
                    catch (Exception ex)
                    {
                        // Capture any errors that happen during startup
                        exceptions.Add(new InvalidOperationException($"Startup assembly {assemblyName} failed to execute. See the inner exception for more details.", ex));
                    }
                }`

**Comment by isualize** [comment]
To be honest i think it's related to https://github.com/aspnet/Hosting/issues/1246

I added this reference to my project a while ago:

<PackageReference Include="Microsoft.AspNetCore.AzureKeyVault.HostingStartup" Version="2.0.2-preview2-final" />

Before that i noticed the same error, but it mentioned the Azure Key Vault dll could not be found.

**Comment by Tratcher** [comment]
@pakrym

**Comment by isualize** [comment]
I understand you are busy, but i havent had an answer in a week. Any updates?

**Comment by pakrym** [comment]
Do you have any site extensions installed? ApplicationInsighths? What version?

**Comment by saithis** [comment]
We got the same exception in our app. After removing the ApplicationInsights site extension from the deployment script, the exception vanished. Any idea how to fix this?

**Comment by pakrym** [comment]
@clguimanMSFT any ideas?

**Comment by clguimanMSFT** [comment]
StartupBootstrapper comes from the "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES" environment variable which is set by the ApplicationInsights site extension.
Is the code running on netcore 2.0 or 2.1?
If it's 2.0 please share the content of the following env variables:
DOTNET_SHARED_STORE & DOTNET_ADDITIONAL_DEPS

**Comment by saithis** [comment]
@clguimanMSFT 
We use asp net core 2.0 with .net framework:

```
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <Platforms>AnyCPU;x64</Platforms>
```

The only DOTNET_... environment variables, that Kudu shows are:
DOTNET_CLI_TELEMETRY_PROFILE = AzureKudu
DOTNET_HOSTING_OPTIMIZATION_CACHE = D:\DotNetCache
DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
Also it doesnt show ASPNETCORE_HOSTINGSTARTUPASSEMBLIES.

**Comment by clguimanMSFT** [comment]
Did you get this variables from Process Explorer => dotnet process?
Did you restart your application after installing the ApplicationInsights extension?

**Comment by saithis** [comment]
@clguimanMSFT I got it from Environment -> environment variables. I didn't know that these are different from the ones under Process Explorer.

In Process Explorer I have these:
- w3wp.exe:
```
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES | StartupBootstrapper
DOTNET_ADDITIONAL_DEPS | D:\Program  Files  (x86)\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\;D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.5.6\core\additionalDeps
DOTNET_SHARED_STORE | D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.5.6\core\store\
```

- SnapshotHolder_x86.exe:
```
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES | StartupBootstrapper
DOTNET_ADDITIONAL_DEPS | D:\Program  Files  (x86)\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\;D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.5.6\core\additionalDeps
DOTNET_SHARED_STORE | D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.5.6\core\store\
```

- My Api exe without any environment variables

**Comment by saithis** [comment]
@clguimanMSFT Yes, it is a self-contained aspnetcore application running on .net framework 4.6.1. We have installed the Microsoft.ApplicationInsights.AspNetCore as a nuget package, but also installed the site extension to get the sql queries in the logs. 

I will try installing the snapshot debugger nuget package when I get back to work on monday, thanks.

**Comment by clguimanMSFT** [comment]
You can still install the extension, but your app shouldn't try and blindly load HostingStartup assemblies. If there's some reason you need to do that, you can just ignore the exception for StartupBootstrapper or explicitly remove that assembly from the list

**Comment by saithis** [comment]
@clguimanMSFT Its the asp net core code that "blindly loads HostingStartup assemblies" in WebHostBuilder.Build(). But setting "hostingStartupExcludeAssemblies" to "StartupBootstrapper" should exclude that assembly then, right? Can you tell me what the StartupBootstrapper assembly is for? Is there a negative effect for self-contained aspnetcore applications, when it can't be loaded and I just exclude it?

Thanks for the help so far :)

**Comment by clguimanMSFT** [comment]
The StartupBootstrapper assembly is part of ApplicationInsights site extension and it's used to inject ApplicationInsights assemblies in Azure Web Apps. This code detects if ApplicationInsights is already present in the process and will back-off if necessary.
@pakrym can you please help @saithis with the HostingStartup questions?

**Comment by isualize** [comment]
@clguimanMSFT We are using Azure App Services and run the same configuration as @saithis. We are using .net core 2.0 and application insights 2.4.0 and get the same exception in our logs.

Under process i couldnt find anything other then w3wp.
What is the next step to resolve this problem?

**Comment by clguimanMSFT** [comment]
@isualize Are you deploying a self-contained application? If so - please follow the instructions here: https://github.com/aspnet/Hosting/issues/1398#issuecomment-387842930

**Comment by isualize** [comment]
@clguimanMSFT ill give that a try and will get back to you

**Comment by isualize** [comment]
@clguimanMSFT thanks for your help. I installed Microsoft.ApplicationInsights.AspNetCore 2.2.1 and the problem went away. What's the reason we need to install this seperately?

**Comment by clguimanMSFT** [comment]
@isualize were you deploying a self-contained application? Previously you were getting the same exception with 'StartupBootstrapper not found'?

**Comment by Leon99** [comment]
I have a pretty basic .NET Core 2.0 web app deployed as an Azure App Service. I did a deployment today which had no changes compared to a working version that has been online and working for months and suddenly I got 
```
System.InvalidOperationException: Startup assembly Microsoft.AspNetCore.AzureKeyVault.HostingStartup failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.AzureKeyVault.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
```
It doesn't use/reference AzureKeyVault.

**Comment by isualize** [comment]
@clguimanMSFT yes we deployed into an Azure App Service container. We did not get this exception at all using IIS on a virtual machine at our other hosting party.

**Comment by isualize** [comment]
@pakrym Im getting emails if the amount of http error in the last hour are greater than x in Azure. I'd like to know when theyre serious or not. There is a chance i might overlook other errors when i keep facing this issue.

**Comment by vmendi** [comment]
We are running an Azure Web App that we recently upgraded to .net Core 2.1 with Microsoft.ApplicationInsights.AspNetCore  2.3.0.

We are also getting this exception:

```Hosting startup assembly exception  System.InvalidOperationException: Startup assembly StartupBootstrapper failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.     at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)     at System.Reflection.Assembly.Load(AssemblyName assemblyRef)     at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)     --- End of inner exception stack trace --```

**Comment by clguimanMSFT** [comment]
@vmendi The ApplicationInsights site extension is not currently supporting ASP.NET Core 2.1 applications. We'll have a release as soon as possible.
The exception you're seeing is not fatal, and you can ignore it in the meantime.
I'll let you know once the new version of the extension is released

**Comment by clguimanMSFT** [comment]
@vmendi Application Insights extension for Azure App Service 2.6.3 was released - this version supports ASP.NET Core 2.1. Please upgrade to this version

**Comment by clguimanMSFT** [comment]
@PureKrome go to http://<webapp-name>.scm.azurewebsites.net/ApplicationInsights to see the current extension version.
To upgrade you can do one of the following:
1. From the App Service blade in the Azure Portal click on "Application Insights" (on the left, mid screen) and you'll get a banner asking you to upgrade if required.
2. Go to Kudu (from the App Service blade click on "Advanced Toold" on the left) , click on "Site extensions" and you'll see the "Application Insights extension for Azure App Service" which requires an update. After updating click "Restart Site" to restart Kudu and then also restart the App Service to enable the extension for you web app.

**Comment by PureKrome** [comment]
Thanks @clguimanMSFT ! My extension wasn't v 2.6.3 and it did have the upgrade option there :) Upgraded, error went away. Awesome and thanks!

Oh! question .. Do I still need this AI Extension if I've got AppInsights code in my aspnetcore 2.1 web app? Do I need both?

**Comment by clguimanMSFT** [comment]
The site extension also enables some extra features like [Snapshot Debugger](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-snapshot-debugger) and [Application Insights Profiler](https://azure.microsoft.com/en-us/blog/application-insights-profiler/). 
If you want to use these features you'll have to make sure they are enabled. If you installed the site extension through the Application Insights page from the Azure App Service page then you'll have them on by default. If you installed the site extension separately or it has be installed some time ago (before May 2018) you should make sure the Application Insights enablement is properly set so you'll need to go to the Application Insights blade (left side, mid screen) and click "Change": there you can select the same resource you've already used and afterwards you'll need to pick the Runtime and expand Advanced Settings to pick the right options for you. 
![image](https://user-images.githubusercontent.com/22645093/41606816-6fc2cfd4-7399-11e8-8309-c45ba2777e46.png)
After you click "OK" you'll have to scroll up and click "Continue"

If you don't want to use the ApplicationInsights blade you can enable the feature by adding these Application Settings in the portal: APPINSIGHTS_PROFILERFEATURE_VERSION = 1.0.0 (for profiler) , APPINSIGHTS_SNAPSHOTFEATURE_VERSION = 1.0.0 (for snapshot debugger).

**Comment by elvirdolic** [comment]
I have the same issue. We have .net core 2.1 and we have configured app insights (We see everything in app inights). Then I wanted to use the profiler and conntected the app with steps above to app insights. I can see in the profiler in app insights that the app is connected, but I don't see any profiler telemetry data which I would expect. Also profile now is not working. When I check the log files I see following issue:

```
System.InvalidOperationException: Startup assembly Microsoft.AspNetCore.AzureAppServices.HostingStartup failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.AzureAppServices.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
```

**Comment by alexiordan** [comment]
As mentioned here: https://github.com/aspnet/Hosting/issues/1398#issuecomment-387886627

> The StartupBootstrapper assembly is part of ApplicationInsights site extension and it's used to inject ApplicationInsights assemblies in Azure Web Apps. This code detects if ApplicationInsights is already present in the process and will back-off if necessary.

I spent some time to figure it out. 

I got this exception when I was using the extension from Azure together with code reference to ApplicationInsights.

I ended-up removing the extension form Azure and leaving only my project's references to AI:
```
  .UseApplicationInsights()
```
This way, exception was gone.

**Comment by joshmouch** [comment]
I get this exception, too.  It happens when I go to the Performance tab in App Insights, click on the "Profiler" button, then click "Install".
In my case, the app completely stops working at this point.
Then I have to go to http://.scm.azurewebsites.net/ApplicationInsights and click "disable" on the Profiler Web Job, but I can leave the other two enabled.

I also have a self contained Asp.Net core 2.1 app.  However, I want the App Insight Profiler enabled to measure performance.  How do I enable this without bringing my site down?

**Comment by jbaumbach** [comment]
@joshmouch is there any official documentation on that button? The two official docs I could find are either outdated (https://docs.microsoft.com/en-us/azure/application-insights/app-insights-profiler) or the feature is not currently working on Azure (https://blogs.msdn.microsoft.com/appserviceteam/2018/06/06/app-service-diagnostics-profiling-an-asp-net-web-app-on-azure-app-service/).

Despite the lack of docs, I clicked that button you mentioned and the subsequent "Profile Now" button anyway.  But after a few minutes of "The profiling session is in progress", nothing appears to have happened.

The number of seemingly redundant features accompanied by incomplete and outdated documentation is infuriating.

**Comment by joshmouch** [comment]
@jbaumbach This is working for me now after uninstalling from every one of my app services (including slots on the app service), then updating ASP.Net Core extensions to the latest, and then installing the Profiler again.  Somewhere in there, I went in and deleted a bunch of extra folders that were lying around that still had config files in them.  That may have been what fixed it... not sure.

However, I have yet to do another slot swap since it started working, and I think this is originally where the trouble started happening.

**Comment by jbaumbach** [comment]
@joshmouch Thanks for the info.  We got it working too, now the tough part is finding out why we have so many BLOCKED_TIME entries.

**Comment by halkor** [comment]
I'm having the same issue. My app is ASP.NET Core 2.1 using the full .net framework (4.7). Reinstalled everything and using the latest version. Still failing.

**Comment by alincosmin7** [comment]
Hi, does anyone know how to remove the application insight extension? Should I just remove the directory from azure ?

**Comment by clguimanMSFT** [comment]
@alincosmin7  You can remove the site extension by going to the "Extensions" blade under "Development Tools" in the App Service page.

Today we are rolling out a new enablement experience that doesn't require a site extension and fixes some of the existing issues. If you want to try that out you can click on the "Application Insights" link in the "Settings" section and then, from the blade, click on "Turn on site extension". This will remove the old extension and enable the built-in Application Insights enablement.
![image](https://user-images.githubusercontent.com/22645093/48713715-e5b92180-ebc5-11e8-9e7e-b8ac300b281c.png)

**Comment by marcusvnac** [comment]
Hey @clguimanMSFT , I enabled the new Application Insights experience in my App as you said, however, I still get the same error:

`Message: Hosting startup assembly exception Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
`
`Exception: System.InvalidOperationException: Startup assembly StartupBootstrapper failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
 at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
 at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
 at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
 at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
 --- End of inner exception stack trace`

**Comment by clguimanMSFT** [comment]
@marcusvnac what version of .NET Core are you targeting? Is it a self-contained dotnetcore application?
Please share the values of the following environment variables (From Kudu->Process explorer-> Properties on the 'dotnet.exe' process):
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES, DOTNET_ADDITIONAL_DEPS, DOTNET_SHARED_STORE

**Comment by marcusvnac** [comment]
@clguimanMSFT It is a self-contained dotnetcore app. The target FW is netcoreapp2.1.

ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: 
StartupBootstrapper;DiagnosticServices.HostingStartup;StartupBootstrapper;Microsoft.AspNetCore.AzureAppServices.HostingStartup;Microsoft.AspNetCore.Server.IISIntegration

DOTNET_ADDITIONAL_DEPS: D:\Program Files (x86)\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\;D:\Program Files (x86)\SiteExtensions\ApplicationInsightsAgent\2.6.8\core\additionalDeps;D:\Program Files (x86)\SiteExtensions\DiagnosticServices\3.0.2\core\additionalDeps;D:\Program Files (x86)\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\;D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\additionalDeps;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\;D:\Program Files\dotnet\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\

DOTNET_SHARED_STORE:  D:\Program Files (x86)\SiteExtensions\ApplicationInsightsAgent\2.6.8\core\store\;D:\Program Files (x86)\SiteExtensions\DiagnosticServices\3.0.2\core\store\;D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\store\;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\store

**Comment by clguimanMSFT** [comment]
We dont' support self-hosted dotnetcore application. Please read this for possible options: https://github.com/aspnet/Hosting/issues/1398#issuecomment-387842930

**Comment by marcusvnac** [comment]
I have those too. So I just have to disable this App Insights in my App in Azure and I am good to go?

**Comment by clguimanMSFT** [comment]
Yes, but that will also disable Service Profiler.
If you still want to use ServiceProfiler I recommend keeping ApplicationInsights enabled in the Azure App Service, but updating the following App Setting: "**ApplicationInsightsAgent_EXTENSION_VERSION=disabled**". This will disable the SDK injection (the one causing the exception), but it will keep SnapshotCollector injection and ServiceProfiler webjob.

**Comment by marcusvnac** [comment]
I updated the settings, however, I still get the same error. Here is how is set up now:

![image](https://user-images.githubusercontent.com/7533098/49098724-2e5f8300-f235-11e8-94a3-c71987bd97e6.png)

![image](https://user-images.githubusercontent.com/7533098/49098764-459e7080-f235-11e8-8efb-ce065eb39e1c.png)

**Comment by clguimanMSFT** [comment]
Please share ASPNETCORE_HOSTINGSTARTUPASSEMBLIES, DOTNET_ADDITIONAL_DEPS, DOTNET_SHARED_STORE again.
Just to double check: After updating the App Setting and saving the change, you didn't click on "Turn on site extension" again, right?

**Comment by marcusvnac** [comment]
No, I didn't click to re-enable it.

ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: 
DiagnosticServices.HostingStartup;Microsoft.AspNetCore.AzureAppServices.HostingStartup;Microsoft.AspNetCore.Server.IISIntegration
--

DOTNET_ADDITIONAL_DEPS: D:\Program Files (x86)\SiteExtensions\DiagnosticServices\3.0.2\core\additionalDeps;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\;D:\Program Files\dotnet\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\
--

DOTNET_SHARED_STORE: D:\Program Files (x86)\SiteExtensions\DiagnosticServices\3.0.2\core\store\;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\store
--

**Comment by marcusvnac** [comment]
Np. I did what you said and I still get the error: `Hosting startup assembly exception Could not load file or assembly 'DiagnosticServices.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`.

As you said, this is just noise, no fatal exception. By the end, I should leave the AppInsights disabled in the Azure Web App and get it working just by adding the Nuget packages and the startup code to my application, correct?

**Comment by clguimanMSFT** [comment]
You get "DiagnosticServices.HostingStartup" in the exception after clicking on "Turn on site extension", clicking "Save", then turning it off and clicking "Save" again?

When the extension is completely off "DiagnosticServices.HostingStartup" shouldn't be in ASPNETCORE_HOSTINGSTARTUPASSEMBLIES. The only ones left should be "Microsoft.AspNetCore.AzureAppServices.HostingStartup;Microsoft.AspNetCore.Server.IISIntegration" which are controlled by other private site extensions, which you can uninstall from the "Extensions" blade.

Yes, I recommend using the Nuget packages in your self-hosted scenario.

**Comment by marcusvnac** [comment]
Yes, I did that. Enabled and disabled it. I am still getting it after having it disabled and after restarting my app.  I checked the ASPNETCORE_HOSTINGSTARTUPASSEMBLIES and DiagnosticServices.HostingStartup is still there. Maybe there is some problem setting the environment variable.

I will use just the Nuget packages approach. Thank you.

**Comment by clguimanMSFT** [comment]
You also have to manually set all the options in "Instrument your application" to Off.

**Comment by joshmouch** [comment]
@clguimanMSFT 
I'm still getting the "Startup assembly StartupBootstrapper failed to execute." error.  I disabled the Application Insights Site extension and disabled all of the options underneath it.  The odd thing is that I get this exception *after* my EXE has loaded and has been configured in the w3wp.exe process. Here are the environment variables:

```
w3wp.exe:
	ASPNETCORE_HOSTINGSTARTUPASSEMBLIES	StartupBootstrapper;Microsoft.AspNetCore.AzureAppServices.HostingStartup
	
	DOTNET_ADDITIONAL_DEPS	D:\Program Files (x86)\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\;D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\additionalDeps;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\;D:\Program Files\dotnet\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\

	DOTNET_SHARED_STORE	D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\store\;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\store


	SnapshotHolder_x64.exe
		ASPNETCORE_HOSTINGSTARTUPASSEMBLIES	StartupBootstrapper;Microsoft.AspNetCore.AzureAppServices.HostingStartup

		DOTNET_ADDITIONAL_DEPS	D:\Program Files (x86)\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\;D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\additionalDeps;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\;D:\Program Files\dotnet\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\

		DOTNET_SHARED_STORE	D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\store\;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\store

	MyApi.exe
	
		ASPNETCORE_HOSTINGSTARTUPASSEMBLIES	StartupBootstrapper;Microsoft.AspNetCore.AzureAppServices.HostingStartup;Microsoft.AspNetCore.Server.IISIntegration

		DOTNET_ADDITIONAL_DEPS	D:\Program Files (x86)\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\;D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\additionalDeps;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\;D:\Program Files\dotnet\additionalDeps\Microsoft.AspNetCore.AzureAppServices.HostingStartup\

		DOTNET_SHARED_STORE	D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5\core\store\;D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\store
```

**Comment by clguimanMSFT** [comment]
> D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5..
It seems the new enablement page didn't remove the old extension. Probably because you didn't first enable the extension, click "Apply", then disable all the features.
You can either follow the steps above, or just go in the "Extensions" page and remove "Microsoft.ApplicationInsights.AzureWebSites". I recommend doing this while the website is stopped so all files can be removed without any of them being locked by your running process.

**Comment by joshmouch** [comment]
Still getting "StartupBootstrapper failed".
I followed the instructions above.
I stopped the app service, disabled all the Insights features, hit apply, then disabled App Insights, and then hit apply then started the app service back up.
The "D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.5..." is still in there.
I don't have a "Microsoft.ApplicationInsights.AzureWebSites" extension installed.
I *do* have the "ASP.NET Core Extensions | 2.1.1" extension installed.
All the App Insights related App Settings have "disabled" as their values.

Here's what my processes look like:
![image](https://user-images.githubusercontent.com/3098820/49247251-d10a3400-f3e4-11e8-9a40-bfb6595302d0.png)

**Comment by clguimanMSFT** [comment]
@joshmouch you can safely remove the "D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites" folder. This will ensure the extension is properly removed. The new enablement blade should have done that for you, we'll investigate further why that did not happen.
