### ISSUE TITLE
Broken tests: Precompilation_WorksForIndexPage_UsingFileName et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Hosting#1433]
This test [fails](http://aspnetci/viewLog.html?buildId=474415&buildTypeId=Lite_MvcTest) all the time with the following error:
```
System.InvalidOperationException : No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<StartSelfHostAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<DeployAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FunctionalTests.ApplicationTestFixture.<CreateDeploymentAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FunctionalTests.RazorPagesAppTest_Desktop.<Precompilation_WorksForIndexPage_UsingFileName>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test Precompilation_WorksForIndexPage_UsingFileName at 2018-05-24T19:31:40
| [0.002s] TestLifetime Information: Starting test Precompilation_WorksForIndexPage_UsingFileName at 2018-05-24T19:31:40
| [0.002s] TestLifetime Information: Finished test Precompilation_WorksForIndexPage_UsingFileName in 0.0003002s
| [0.008s] TestLifetime Information: Finished test Precompilation_WorksForIndexPage_UsingFileName in 0.0071013s
```
These failures seem to have started after [these](http://aspnetci/viewLog.html?buildId=473853&tab=buildChangesDiv&buildTypeId=Lite_MvcTest) changes.

**Comment by pranavkm** [comment]
Can this be closed? Think we fixed this no?
