### ISSUE TITLE
Obscure UseSetting call causes System.ArgumentException in WebHostBuilder.BuildCommonServices

### ISSUE THREAD

**Issue by kierenj** [aspnet/Hosting#1439]
This is just something that popped up as a side-effect of a bug in my own code.

Calling `.UseSetting("WebApi", "")` on a `WebHostBuilder` as a part of well, building a web host, causes:

```
Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: WebApi
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider..ctor(MemoryConfigurationSource source)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```

**edit** Note: the case-insensitivity of config combined with the case-sensitivity of dictionaries meant that my bug - calling `.UseSetting("webApi", "")` - did *not* cause this exception if the underlying config section was `"webApi"` and not `"WebApi"`.

It's a weird thing to do, but still, it happened to me, in implementing a workaround for #839 .  Not sure if this is one you'd want to defend against?

**Comment by muratg** [comment]
@kierenj Could you please take a look at https://github.com/aspnet/Extensions/pull/503/files? It may have fixed your issue already.

If not, please file an issues in Extensions repo, because this looks like a Config issue, and not a hosting one.
