### ISSUE TITLE
host.RunAsService() throws PlatformNotSupportedException on Windows

### ISSUE THREAD

**Issue by cheesi** [aspnet/Hosting#1535]
Hello!

I'm facing a very strange issue. Currently I'm porting our .Net Framework windows service to ASP.NET Core. For the windows service part, i have been following this tutorial: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1

However the `host.RunAsService()` throws a `PlatformNotSupportedException `on my windows dev machine (i didn't had the time to test it somewhere else).

```
System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceBase..ctor()
   at Microsoft.AspNetCore.Hosting.WindowsServices.WebHostService..ctor(IWebHost host)
   at Codatex.TerminalServer.Program.Main(String[] args) in C:\Users\user\source\repos\Project\src\Project.Server\Program.cs:line 63
```

The code isn't very spectacular:
```
IsService = args.Contains(RUN_AS_SERVICE);
ContentRoot = IsService ? Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName) : Directory.GetCurrentDirectory();
Logger = NLogBuilder.ConfigureNLog(Path.Combine(ContentRoot, NLOG_CONFIG)).GetCurrentClassLogger();
var host = CreateWebHostBuilder(args.Where(x => x != RUN_AS_SERVICE).ToArray()).Build();
                
if (IsService)
{
    Logger.Info("Starting as a service.");
    host.RunAsService();
}
else
{
    Logger.Info("Starting in console mode.");
    host.Run();
}
```

Info:
```
ASP.NET Core 2.1.2 with Microsoft.AspNetCore.Hosting.WindowsServices 2.1.1.
Windows 10.0.17134 
C:\Users\user>dotnet --version
2.1.400
```

**Comment by muratg** [comment]
@cheesi Interesting. Were you able to try any other Windows machine? 

Also, are you able to creaate an isolated repro app so that we can investigate on our side?

**Comment by cheesi** [comment]
As I already mentioned, I didn't had the time to test it on another windows machine, but i will try that now.

The code of the application is closed company source, so I'm not really able to share much of it, but I will setup a new ASP.NET Core project with windows service hosting and try to figure out, if it's the code of our application or my dev machine.

**Comment by muratg** [comment]
@cheesi sounds good, thanks!

**Comment by cheesi** [comment]
I tried it on a second dev machine now and I got the same error. I going to setup a fresh repo now.

**Comment by cheesi** [comment]
I figured out the problem.

I was publishing with VS and my publish profile set to "Framework Dependent", but it seems to only work with "Self Contained". 

Is there a specific reason for that?

**Comment by muratg** [comment]
@cheesi interesting. @Tratcher thoughts?

**Comment by Tratcher** [comment]
It should work either way. It sounds like the right dependency isn't getting published. We do depend on a special dependency out of the Windows Compat Pack, System.ServiceProcess.ServiceController, so if that's not getting published and you end up with a placeholder that would explain the PlatformNotSupportedExceptionon.

Do you have a project handy you can share on github? Or is it just one of the doc sample apps?

**Comment by cheesi** [comment]
I set up a new ASP.NET repo with windows service hosting and that worked with both publish options. Unfortunately, i got two very important tasks today, so I need to put this on hold.  When i have more time, I will continue investigating this issue.

**Comment by shivashankar-awanti** [comment]
@cheesi did you find the issue what was causing, as im facing the same issue now, i tried changing to self contained still facing the same error, here im running the solution in AKS cluster, getting the same error, what is ideal setting for publishing dotnet core app on Azure AKS container.

Unhandled Exception: System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceBase..ctor()

**Comment by cheesi** [comment]
@shivashankar-awanti sorry, I didn't had the time to investigate this error further. Currently I have so many tasks. I will share any infos here, if I know something new.

**Comment by muratg** [comment]
@shivashankar-awanti this bug is about Windows. I'm assuming you're running Linux containers in your AKS cluster.

**Comment by shivashankar-awanti** [comment]
@muratg yes, the containers are Linux. Is there any solution for this bug?

**Comment by davidfowl** [comment]
@shivashankar-awanti don't use the RunAsService method, it's specifically for Windows services. Use Run instead.

**Comment by shivashankar-awanti** [comment]
@davidfowl im using ServiceBase.Run(servicesToRun) to start the service.

**Comment by davidfowl** [comment]
Why are you using ServiceBase at all on linux, don't use it, it isn't for that purpose. Just use the normal Run method.

**Comment by shivashankar-awanti** [comment]
@davidfowl  under which namespace is Run method which you are talking about, as im writing in this way by creating list of services which needs to be run as a instance of ServiceBase and im looping it to run one by one. if i dont use ServiceBase, what would be other approach.

**Comment by davidfowl** [comment]
@shivashankar-awanti I'm not sure what you're trying to do. Are you trying to write a console application on linux?

**Comment by shivashankar-awanti** [comment]
@davidfowl  yes, but noraml console appn works but when im trying to use ServiceBase its causing issue.

**Comment by cheesi** [comment]
ServiceBase is WINDOWS ONLY. It is there to interact with WINDOWS service interface. IT IS NOT FOR LINUX.

**Comment by shivashankar-awanti** [comment]
@cheesi and @davidfowl  Thanks for the info, but is there any other way to implement, same as ServiceBase which supports Linux Container.

**Comment by FrankPeach** [comment]
@cheesi were you able to get this working as "Framework Dependent"? I am having the same issue and I did make sure that System.ServiceProcess.ServiceController.dll was being published.

**Comment by cheesi** [comment]
Hey @FrankPeach!
Nay, sorry. As this is just my side project and I had so many other things todo, I still didn't had the time to investigate this issue.

One possibility might be to wait for .NET Core 3.0, as there will be changes regarding the build/publish tasks.

Let me know, if you got anything new.
