### ISSUE TITLE
Hosting is not able to load Microsoft.AspNet.Hosting.ini file

### ISSUE THREAD

**Issue by rustd** [aspnet/Hosting#277]
I have a sample which has the following in web command and hosting file. This does not work today.
```C#
"web": "Microsoft.AspNet.Hosting",
```
and the following in Microsoft.AspNet.Hosting.ini
```C#
[Microsoft.AspNet.Hosting]
server=Microsoft.AspNet.Server.WebListener
server-urls=http://localhost:5000

```

```C#
System.InvalidOperationException: Unable to resolve path 'Microsoft.AspNet.Hosting.ini'; construct
his IConfigurationSourceRoot with a non-null BasePath.
   at Microsoft.Framework.ConfigurationModel.Helper.ConfigurationHelper.ResolveConfigurationFilePat
(IConfigurationSourceRoot configuration, String path)
   at Microsoft.Framework.ConfigurationModel.ConfigurationExtensions.AddIniFile(IConfigurationSourc
Root configuration, String path, Boolean optional)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] arg
, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationN
me, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] arg
, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
Press any key to continue . . .
```

**Comment by rustd** [comment]
@muratg this is for Beta5 for the templates

**Comment by Tratcher** [comment]
FYI: The expected key names are:
```
server=Microsoft.AspNet.Server.WebListener
server.urls=http://localhost:8080
```
or
```
Hosting:Server=Microsoft.AspNet.Server.WebListener
server.urls=http://localhost:8080
```

**Comment by rustd** [comment]
@Tratcher I tried this and I got this error
```C#
System.InvalidOperationException: IHostingBuilder.UseServer() is required for Start()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args
, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationNa
me, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args
, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

**Comment by Tratcher** [comment]
Using what packages? Coherence hasn't published a build in days. Or are you using volatile?
