### ISSUE TITLE
Provide a better error message when the webroot folder does not exist

### ISSUE THREAD

**Issue by danroth27** [aspnet/Hosting#278]
```
C:\Users\danroth27\Documents\Visual Studio 14\Projects\WebApplication18\src\WebApplication18>dnx . web
System.IO.DirectoryNotFoundException: C:\Users\danroth27\Documents\Visual Studio 14\Projects\WebApplication18\src\WebApplication18\wwwroot\
   at Microsoft.AspNet.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNet.Hosting.HostingEnvironment..ctor(IApplicationEnvironment appEnvironment)
   at Microsoft.AspNet.Hosting.HostingEngine..ctor(IServiceProvider fallbackServices)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
```

**Comment by Tratcher** [comment]
Dupe of https://github.com/aspnet/Hosting/issues/233
