### ISSUE TITLE
IIS publishing - Couldn't determine an appropriate version of KRE

### ISSUE THREAD

**Issue by sujitdmello** [aspnet/Hosting#281]
Published a web API as follows:

*dnu publish --no-source --out c:\inetpub\wwwroot\ToDoApi --runtime dnx-clr-win-x64.1.0.0-beta5-11781*

Go to c:\inetpub\wwwroot\ToDoApi folder and run *web.cmd* or *kestrel.cmd* - app works great. Configure IIS to point to the *c:\inetpub\wwwroot\ToDoApi\wwwroot* folder and try to access the app via *http://localhost/ToDoApi/default.html* - I get an error:

```
Exception type: InvalidOperationException 
    Exception message: Couldn't determine an appropriate version of KRE to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.
   at AspNet.Loader.KRuntimeLocator.LocateKRuntime(MapPathHelper mapPathHelper, Boolean& isCoreClr, String& relativeAppBasePath)
   at AspNet.Loader.Bootstrapper.LoadApplication(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.ProcessHost.System.Web.Hosting.IProcessHostLite.ReportCustomLoaderError(String appId, Int32 hr, AppDomain newlyCreatedAppDomain)
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)
```
In case it helps, below is the output of the *dnvm list* command:

```
Active Version           Runtime Architecture Location                       Alias
------ -------           ------- ------------ --------                       -----
       1.0.0-beta5-11744 clr     x86          C:\Users\nbkdv7c\.dnx\runtimes
       1.0.0-beta5-11749 clr     x86          C:\Users\nbkdv7c\.dnx\runtimes
       1.0.0-beta5-11760 clr     x86          C:\Users\nbkdv7c\.dnx\runtimes
       1.0.0-beta5-11781 clr     x64          C:\Users\nbkdv7c\.dnx\runtimes
  *    1.0.0-beta5-11781 clr     x86          C:\Users\nbkdv7c\.dnx\runtimes default
```

**Comment by Tratcher** [comment]
That error message says "KRE" which tells me you're trying to use a beta4 build of Microsoft.AspNet.Server.IIS. You need to update all of your packages to beta5 to run with the beta5 dnx.

**Comment by sujitdmello** [comment]
Correct! Was also missing a reference to Microsoft.AspNet.Server.IIS in project.json.

Thanks!
