### ISSUE TITLE
Strongly-named assembly issue when running an app

### ISSUE THREAD

**Issue by csunali** [aspnet/Hosting#465]
I don't know if it is just me doing something wrong but after upgrading to the latest dev bits via `aspnetcidev` feed, I get the following exception when I try to run an application.

DNX runtime: dnx-clr-win-x64.1.0.0-rc1-16048
Microsoft.Extensions.PlatformAbstractions: 1.0.0-rc2-16107

Exception:

```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
File name: 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()


System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

**Comment by Tratcher** [comment]
I think you need to update your DNX to rc2.

**Comment by csunali** [comment]
I tried that - if I am not doing something wrong - the latest runtime version seems to be RC 1.

```
C:\Windows\system32>dnvm install -r coreclr -a x86 -p latest -u
Determining latest version
'dnx-coreclr-win-x86.1.0.0-rc1-16048' is already installed in C:\Users\Coskun\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-16048.
Adding C:\Users\Coskun\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-16048\bin to process PATH
Adding C:\Users\Coskun\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-16048\bin to user PATH

C:\Windows\system32>dnvm install -r coreclr -a x64 -p latest -u
Determining latest version
'dnx-coreclr-win-x64.1.0.0-rc1-16048' is already installed in C:\Users\Coskun\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-16048.
Adding C:\Users\Coskun\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-16048\bin to process PATH
Adding C:\Users\Coskun\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-16048\bin to user PATH
```

The commands above are for core clr but it is the same for clr.

What do you think I am doing wrong?

**Comment by Tratcher** [comment]
Ah, you may be pulling DNX and packages form different feeds. dnvm doesn't honor nuget.config, you have to override the DNX_UNSTABLE_FEED to change which feed it uses.

**Comment by csunali** [comment]
That certainly helped me be able to install RC 2 of DNX! I did not know about that variable.

Thank you!
