### ISSUE TITLE
Using an active logger (not NullLogger) with TestHost results in a null ref

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Hosting#532]
From https://github.com/aspnet/Mvc/pull/3796#discussion_r48160786. Here's the stack trace:

```C#
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at Microsoft.AspNet.Http.Internal.DefaultHttpRequest.get_Protocol()
   at Microsoft.AspNet.Hosting.Internal.HostingLoggerExtensions.HostingRequestStarting.ToString()
   at Microsoft.AspNet.Hosting.Internal.HostingLoggerExtensions.HostingRequestStarting.<>c.<.cctor>b__7_0(Object state, Exception exception)
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
```

**Comment by JunTaoLuo** [comment]
Merged to dev
