### ISSUE TITLE
Deploy to Azure - Kestrel got "ECONNRESET"error after first 100 requests

### ISSUE THREAD

**Issue by up2pixy** [aspnet/Hosting#555]
I'm using rc1-final. The API is running on my local IIS w/o any problem. But when I published it to Azure and did some load testing, I could only got first 100 request returned correctly, and all following requests were returning with error 502: "The specified CGI application encountered an error and the server terminated the process."

Then I checked the log of my API on Azure. I got following error:
```
warn: Microsoft.AspNet.Server.Kestrel[0]
      Connection processing ended abnormally
      Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Microsoft.AspNet.Server.Kestrel.Http.ISocketOutput.Write(ArraySegment`1 buffer, Boolean immediate)
         at Microsoft.AspNet.Server.Kestrel.Http.Frame.WriteChunkedResponseSuffix()
         at Microsoft.AspNet.Server.Kestrel.Http.Frame.<ProduceEnd>d__96.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
```
Is there anything I missed when I publish to Azure. The queue size? concurrent user size? Or it's a bug between Kestrel and Azure hosting environment? I was wondering if it's related with this article: http://blogs.msdn.com/b/cie/archive/2014/09/09/502-exception-while-connecting-with-service-bus-relay-endpoint-during-load-test-with-more-than-100-concurrent-users.aspx

Please help... Thank you!

**Comment by up2pixy** [comment]
This is Azure Service Bus Limits: Subsequent requests for additional connections will be rejected and an exception will be received by the calling code. REST operations do not count towards concurrent TCP connections. Capped by the limit of concurrent connections per namespace. And Maximum number of namespaces per Azure subscription is 100
