### ISSUE TITLE
NRE when logging through the test host server

### ISSUE THREAD

**Issue by fermaem** [aspnet/Hosting#578]
version: 1.0.0-rc2

The code below fails with a NRE when ran through `dnx test`

```
PS Z:\test\ClassLibrary1> dnx test
xUnit.net DNX Runner (64-bit DNXCore 5.0)
  Discovering: ClassLibrary1
  Discovered:  ClassLibrary1
  Starting:    ClassLibrary1
    ClassLibrary1.LogIssueFixture.tada [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
           at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
        F:\Axa\log-issue\test\ClassLibrary1\TestServerFixture.cs(27,0): at ClassLibrary1.LogIssueFixture.tada()
        ----- Inner Stack Trace -----
           at Microsoft.AspNet.Http.Internal.DefaultHttpRequest.get_Protocol()
           at Microsoft.AspNet.Hosting.Internal.HostingLoggerExtensions.HostingRequestStarting.ToString()
           at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
           at Microsoft.Extensions.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
  Finished:    ClassLibrary1
=== TEST EXECUTION SUMMARY ===
   ClassLibrary1  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.273s
```

A tiny sub-question, why ~~is~~ isn't this exception caught by the `app.UseExceptionHandler()`?

**Fixture.cs**
```csharp
using System;
using System.Net;
using System.Net.Http;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.TestHost;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Xunit;

namespace ClassLibrary1
{
    public class LogIssueFixture
    {
        [Fact]
        public void tada()
        {
            var builder = new WebApplicationBuilder()
                .UseStartup<Startup>();

            using (var _testServer = new TestServer(builder))
            using (var httpClient = _testServer.CreateClient())
            {
                var req = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/log"));
                var rep = httpClient.SendAsync(req).Result;

                Assert.Contains("Logged on", rep.Content.ReadAsStringAsync().Result);
                Assert.Equal(HttpStatusCode.OK, rep.StatusCode);
            }
        }
    }

    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .AddJsonFile("logging.json");

            Configuration = builder
                .Build();
        }

        public IConfigurationRoot Configuration { get; set; }

        // This method gets called by the runtime. Use this method to add services to the container
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline
        public void Configure(
            IApplicationBuilder app, IHostingEnvironment env,
            ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("logging"));

            app.UseExceptionHandler(errorApp =>
            {
                errorApp.Run(async context =>
                {
                    await context.Response.WriteAsync("{\"error\":\"boom\"}");
                });
            });

            app.Run(
                context => context.Response.WriteAsync(string.Format("Logged on {0}", DateTimeOffset.Now)));
        }
    }
}
```

**project.json**
```json
{
    "version": "0.0.1-*",
    "compilationOptions": {
        "warningsAsErrors": true
    },
    "description": "ClassLibrary1 Class Library",
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",
    "frameworks": {
        "dnxcore5.0": { }
    },
    "commands": {
        "test": "xunit.runner.dnx"
    },
    "dependencies": {
        "Microsoft.AspNet.TestHost": "1.0.0-*",
        "xunit": "2.2.0-*",
        "Microsoft.CSharp": "4.0.1-*",
        "System.Collections": "4.0.11-*",
        "System.Linq": "4.0.1-*",
        "System.Runtime": "4.0.21-*",
        "System.Threading": "4.0.11-*",
        "xunit.runner.visualstudio": "2.2.0-*",
        "xunit.runner.dnx": "2.1.0-*",
        "Microsoft.AspNet.WebApi.Client": "5.2.3",
        "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-rc2-*"
    }
}
```

**Comment by davidfowl** [comment]
> version: 1.0.0-rc2

That's not the right version because it doesn't exist. To find the correct version look in the `project.lock.json` file. 

This was also fixed in the latest builds, see https://github.com/aspnet/Hosting/issues/532

**Comment by fermaem** [comment]
>> version: 1.0.0-rc2

> That's not the right version because it doesn't exist. To find the correct version look in the project.lock.json file.

Sorry. I was unclear. I was just trying to state that it was related to rc2 bits.

>This was also fixed in the latest builds, see #532

Awesome! Thanks for the link. Any idea when is this going to be released on the myget feed?

>A tiny sub-question, why isn't this exception caught by the app.UseExceptionHandler()?

Just for my information, could you please help me understand this? ^^

**Comment by davidfowl** [comment]
> Awesome! Thanks for the link. Any idea when is this going to be released on the myget feed?

Don't have an exact ETA it should be there soon.

> A tiny sub-question, why isn't this exception caught by the app.UseExceptionHandler()?

The error is happening *super early*, since it was a bug in the ASP.NET hosting layer itself, your exception handler middleware didn't get a chance to see it. It happened before even calling into the built pipeline.

**Comment by fermaem** [comment]
Awesome feedback! :heart_eyes:
