### ISSUE TITLE
An unhandled exception has occurred: Sequence contains no matching element

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Hosting#632]
"dotnet run" fails, but "dnx web" works.
dnx: 1.0.0-rc2-16595
dotnet:1.0.0-beta-001694

Error message:
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/Downloads
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Sequence contains no matching element
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JObject root)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultAssemblyProvider..ctor(IApplicationEnvironment environment)
--- End of stack trace from previous location where exception was thrown ---

**Comment by davidfowl** [comment]
/cc @pakrym. 

This is a known issue and was fixed here https://github.com/dotnet/cli/commit/85b7336529049ec78fa76b7c7e6e11833a4dc32d.
