### ISSUE TITLE
Method not found exception when creating a TestServer

### ISSUE THREAD

**Issue by bbehrens** [aspnet/Hosting#670]
### Title
I'm getting a method not found exception when trying to create a TestServer for testing my application

```
at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.TestHost.TestServer..ctor(IWebHostBuilder builder)
   at SelfService.Testing.Bootstrap.TestServerHost..ctor() in C:\code\hr-self-service\test\SelfService.Testing\Bootstrap\TestServerHost.cs:line 24
Result Message:	Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
```

### Functional impact
Can't create a test server for hosting tests

### Minimal repro steps
My Test class:

```
    public class TestServerHost
    {
        TestServer _server;
        HttpClient _client;
        

        public TestServerHost()
        {

            var hostBuilder = new WebHostBuilder()
                .UseCaptureStartupErrors(true);
                
                
            _server = new TestServer(hostBuilder);
            _client = _server.CreateClient();
        }

        [Fact]
        public async Task ReturnHome()
        {
            var response = await _client.GetAsync("/");
            response.EnsureSuccessStatusCode();
        }
    }
```

My project.json

```
{
  "authors": [ "bbehrens" ],
  "commands": {
    "test": "xunit.runner.aspnet"
  },
  "compilationOptions": {
    "warningsAsErrors": true
  },
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-23826",
    "xunit": "2.2.0-beta1-build3239",
    "StructureMap.Dnx": "0.5.1-rc1-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "xunit.runner.dnx": "2.1.0-rc1-build204",
    "xunit.runner.aspnet": "2.0.0-aspnet-rc2-20214",
    "xunit.runner.visualstudio": "2.2.0-beta1-build1144",
    "Microsoft.AspNet.TestHost": "1.0.0-*",
    "SelfService": "1.0.0-*"
  },
  "description": "SelfService.Testing Class Library",
  "frameworks": {
    "dnx451": {
      "dependencies": {
        "Microsoft.AspNetCore.Testing": "1.0.0-*",
        "Microsoft.NETCore.Platforms": "1.0.1-rc2-23826",
        "RhinoMocks": "3.6.1",
        "xunit.runner.aspnet": "2.0.0-aspnet-*",
        "AWSSDK.DynamoDBv2": "3.1.3",
        "Newtonsoft.Json": "8.0.3",
        "RestSharp": "105.2.3"
      }
    }
  },
  "licenseUrl": "",
  "projectUrl": "",
  "tags": [ "" ],
  "version": "1.0.0-*"
}
```

SDK Version 1.0.0-rc2-16595

### Expected result
Test server created to host tests

### Actual result
I get the above stack trace

### Further technical details

**Comment by Tratcher** [comment]
You're mixing versions. Make everything RC2 or just *. Also, don't mix Ms.AspNet and Ms.AspNetCore packages, update them all to AspNetCore.

**Comment by bbehrens** [comment]
/facepalm

Thanks
