### ISSUE TITLE
Loading `hosting.json` fails silently on OS X

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Hosting#761]
I've been struggling with problem on what happended to `hosting.json`. I was pointed to changes to default configuration and this discussion:https://github.com/aspnet/Hosting/issues/737. I've rewritten code and still nothing. Maybe I misunderstood something but I'm adding configuration to Program.cs (following aspnet/Templates content):
```
public static void Main(string[] args)
{
    var config = new ConfigurationBuilder()  
      .AddJsonFile("hosting.json", optional: true)
      .AddEnvironmentVariables(prefix: "ASPNETCORE_")
      .AddCommandLine(args)
      .Build();

    var host = new WebHostBuilder()
        ..UseConfiguration(config)
        .UseUrls(Environment
  .GetEnvironmentVariable("ASPNETCORE_URLS"))
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```
Above does not work and configuration from `hosting.json` is not used to configure host.
The problem seems to be that AddJsonFile cannot read at all files within main, quickly tested with:
```
.AddJsonFile("hosting.json", optional: false)
```
- this results in exception and failure:
```
dotnet run
Project StarterWeb (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'hosting.json' was not found and is not optional.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at StarterWeb.Program.Main(String[] args)
```
Using full path does not help:
```
.AddJsonFile(Path.Combine(Directory.GetCurrentDirectory(), "hosting.json"), optional: false)
```
```
Unhandled Exception: System.IO.FileNotFoundException: The configuration file '/Users/piotrblazejewicz/git/recipes/src/gulp-dotnet-browser-sync/StarterWeb/hosting.json' was not found and is not optional.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at StarterWeb.Program.Main(String[] args)
```
Thanks!

**Comment by davidfowl** [comment]
You need to actually use the configuration you setup by calling UseConfiguration

```C#
var config = new ConfigurationBuilder()  
      .AddJsonFile("hosting.json", optional: true)
      .AddEnvironmentVariables(prefix: "ASPNETCORE_")
      .AddCommandLine(args)
      .Build();

    var host = new WebHostBuilder()
        ...
        .UseConfiguration(config)
         ...
        .Build();

    host.Run();
```

**Comment by peterblazejewicz** [comment]
@davidfowl Thank! I've been updating snippet
No, that's not that problem. I've found a tip here:
https://github.com/aspnet/Configuration/issues/421#issuecomment-206569908
I had to explicitly call SetBasePath:
```
.SetBasePath(Directory.GetCurrentDirectory())
```
```
var config = new ConfigurationBuilder()
  .SetBasePath(Directory.GetCurrentDirectory())  
  .AddJsonFile("hosting.json", optional: true)
  .AddEnvironmentVariables(prefix: "ASPNETCORE_")
  .AddCommandLine(args)
  .Build();

var host = new WebHostBuilder()
    .UseConfiguration(config)
    .UseUrls(Environment
.GetEnvironmentVariable("ASPNETCORE_URLS"))
    .UseKestrel()
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseIISIntegration()
    .UseStartup<Startup>()
    .Build();

host.Run();
```
Thanks!
