### ISSUE TITLE
ApplicationDeployer fails with InvalidOperationException in VS2017 tests

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Hosting#912]
Attempting to migrate MusicStore to VS 2017. The E2E tests fail with this error:

```
System.InvalidOperationException : No process is associated with this object.
Stack Trace:
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.ShutDownIfAnyHostProcess(Process hostProcess)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.Dispose()
   at E2ETests.SmokeTests.<SmokeTestSuite>d__2.MoveNext() in C:\dev\Universe\MusicStore\test\E2ETests\SmokeTests.cs:line 208
```

Repro: https://github.com/aspnet/MusicStore/blob/fbd6cee23e4f8a31944ec6293316e3e19ea05ae7/test/E2ETests/SmokeTests.cs

**Comment by natemcmaster** [comment]
cc @BrennanConroy  any ideas?

**Comment by natemcmaster** [comment]
Found the issue. This error occurs when the process fails to start because the ProcessStartInfo was incorrect.
