### ISSUE TITLE
Setting ASPNETCORE_ENVIRONMENT to the value containg '.' (dot char) gives "Invalid environment setting" error

### ISSUE THREAD

**Issue by ctrl-brk** [aspnet/Hosting#977]
When hosted by IIS, at
```
var builder = new ConfigurationBuilder()
    .SetBasePath(env.ContentRootPath)
    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
```
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: a.b
```

If I remove the dot (and rename settings file accordingly) everything works just fine.

**Comment by Tratcher** [comment]
What was the actual exception type and message?

**Comment by ctrl-brk** [comment]
Application startup exception: System.InvalidOperationException: Invalid environment setting 'a.b'

**Comment by cesarbs** [comment]
I cannot repro your issue. Can you post a repro app for us to debug?

**Comment by ctrl-brk** [comment]
I'm really sorry but the issue was between the chair and the keyboard ;)

**Comment by cesarbs** [comment]
Haha, alright then. Will close.
